### ISSUE TITLE
how to setting kafka.maxRatePerPartition in snappy-job 

### ISSUE THREAD

**Issue by lichar-cheng** [SnappyDataInc/snappydata#1019]
i use snappy-job submit my app, 
but i want to limit rate from kafka,
like spark setting
 .set("spark.streaming.kafka.maxRatePerPartition", s"$maxRatePerPartition")

but snappyjob don't have setting
i try to setting like this:
class SnappySQLLogAggregatorJob extends SnappyStreamingJob {

  override def runSnappyJob(snsc:SnappyStreamingContext,jobConfig: Config): Any = {
snsc.sparkContext.getConf.set("spark.streaming.kafka.maxRatePerPartition",s"$maxRatePerPartition")
.....
}
but it doesn't work
how can i set some config to sparkcontext or  others?

**Comment by lichar-cheng** [comment]
i got it

we can setting '-spark.streaming.kafka.maxRatePerPartition=1000'   at conf/leads ,it's work

and we can't setting it  at snappy-job submit shell

**Comment by zj619** [comment]
lichar-cheng, I have some question about Snappydata, can you give your emai to me?Thank you!
