### ISSUE TITLE
can I execute spark sql  by jdbc driver?

### ISSUE THREAD

**Issue by jessyZu** [SnappyDataInc/snappydata#1065]
can i execute spark sql  by jdbc driver? 
And how to bulk insert data  with low latency?

**Comment by sumwale** [comment]
@jessyZu 

Yes, you can run SparkSQL using the JDBC driver. The dialect supported by Snappy compatible with Spark SQL (some minor differences to make it more SQL standard compliant).

The best way to bulk insert is either using Spark DataFrameWriter APIs in jobs, or using EXTERNAL table and reading from it using JDBC:

```sql
create external table staging_table1 using parquet (path '...');
insert into table1 as select * from staging_table1;
```

See the docs for more details (https://snappydatainc.github.io/snappydata/howto/load_data_into_snappydata_tables/).

**Comment by sumwale** [comment]
@jessyZu A lot of external data sources are supported out of the box. Apart from parquet/csv/orc, all data sources having JDBC access can be accessed using "jdbc" data source. See the section in Spark docs for inbuilt sources: https://spark.apache.org/docs/2.1.1/sql-programming-guide.html#data-sources (note that hive meta-store is not directly supported since product already uses hive catalog internally but there is a programmatic way possible).

**Comment by jessyZu** [comment]
Thanks . I'm new to snappydata, give our usescase :
1.we extract  user's feature data from user's origin data for machine learning by hive sql ;
2.the hive table is  synced from  online db ,and the feature data is computed by java code  ;
3.we want to unify the computation of feature data between OLTP and OLAP  , by spark sql; 
so we consider to use snappydata to persist user's origin data in memory, and  then compute the feature data by spark sql.
bulk insert  user's origin data with low latency ->  submit  multi spark sql to get result

Would snappy fit our usecase? What problems should we pay attention to?

**Comment by piercelamb** [comment]
Hi @jessyZu 

It definitely sounds like a good fit for SnappyData. For more real time answers to questions you should check out our Slack chat: http://snappydata-slackin.herokuapp.com/. There is also a nascent SnappyData community in China; you should check out http://snappydata.club/ and https://snappydata-cn.github.io/.  Most of the users running those sites are on our Slack and are advanced SnappyData users.

**Comment by jramnara** [comment]
To make sure I understand ... here is what you would like to do ?

1) currently, your app relies on some OLTP DB to capture "origin data"
2) you will also write this data directly into SnappyData ?
3) data accumulates in snappydata and periodically you will featurize your
data set and prep for ML ?
4) Does the user also need to run OLAP queries on this data ?


-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://www.snappydata.io/download>

**Comment by jessyZu** [comment]
@jramnara 
yes,you're right. 
we just need to run OLTP queries on the data in snappydata. 
1.OLAP analysis is performed by our data-scientists  , they use hive sql to extract feature for ML. 
2.Currently,we use postgreSQL db to persist user's origin data, but pg sql is not compatible with hive sql, otherwise，the perfomance is not satisfied our business.

Another question, if the schema of user's origin data changed (may add a new column in the future),can snappy table be schema free without recreating a table?
