### ISSUE TITLE
how to set ttl for column table? 

### ISSUE THREAD

**Issue by jessyZu** [SnappyDataInc/snappydata#1069]
@sumwale  
how to set ttl for column table? Expiry for Column table is not supported .In my business,the data can be expired after 1 hour，snappy is just a memory-computation engine for me.

**Comment by sumwale** [comment]
Right now expiry is not supported in column tables. You can add a timestamp column in the required tables and then run a periodic job that will purge the data using something like "delete from table1 where tscol < current_timestamp - interval 1 hour"
