### ISSUE TITLE
is there any plan to support CREATE PROCEDURE like other db?

### ISSUE THREAD

**Issue by jessyZu** [SnappyDataInc/snappydata#1093]
is there any plan to support CREATE PROCEDURE like other db

**Comment by kneeraj** [comment]
We were not thinking of adding this in the near future or may be not at all. The reason being that you can submit jobs in which you can write both sql and scala/java code. Can you please let us know why that might not suffice or job is good enough for your use case also?

**Comment by jessyZu** [comment]
There are many sql to submit,which do real-time ETL-JOB in my case, and everytime to insert data,need to do prepareStatement on JDBC connection,it is a waste of time,may be CREATE PROCEDURE instead of it can bring perfomance improvement.

**Comment by rishitesh** [comment]
@jessyZu Can't you use Spark code to do your ETL? That would much more performant than JDBC route. All such ETL transformation should be encapsulated in a Snappy job & submitted.  Your use case is exactly the situation where Snappy jobs come in handy. Moreover, you get Spark's rich API support to do your ETL.

**Comment by jessyZu** [comment]
@rishitesh  is there an  internal restful api to submit snappy job ? 
as I know,a spark-job-server is serving inside the primary lead node , but if we have a second lead node for HA , how to locate the service endpoint to request？

**Comment by jramnara** [comment]
@jessyZu though we are yet to certify the Job Server Rest API, you can try it as outlined [here](https://github.com/SnappyDataInc/spark-jobserver).  In fact, your rest call can add a 'sync=true' to get a synchronous response from the server (sort of like a procedure). Note that you should NOT create any other context (will likely fail). 
For failover, it would need to be your client code that switches to use the alternate host running the secondary lead. You could use a load balancer like nginx so this occurs automatically.
