### ISSUE TITLE
did Snappy data support secondary lead?

### ISSUE THREAD

**Issue by xiaobogaga** [SnappyDataInc/snappydata#1107]
The Snappy data documentation gives a short description about its **secondary lead** at http://snappydatainc.github.io/snappydata/best_practices/ha_considerations/. However, there is **no detail**
about how to config the secondary lead of snappy data and I couldn't find any property or any other words talking about this.

Did Snappy data suppport secondary lead, if so, **can anybody give a detail such as how to config to use it**?

**Comment by ashetkar** [comment]
To launch multiple lead nodes, you need to add required number of entries in `conf/leads`. Below example launches two leads (one on node-l1 and another on node-l2). When the cluster is launched using `sbin/snappy-start-all.sh`, one of them becomes primary and another secondary lead.

Example:
> $ cat conf/leads
> node-l1 -heap-size=4096m -locators=node-b:8888,node-a:9999
> node-l2 -heap-size=4096m -locators=node-b:8888,node-a:9999

**Comment by xiaobogaga** [comment]
Thank you, I get it.
