### ISSUE TITLE
smart connector mode on spark-k8s

### ISSUE THREAD

**Issue by thbeh** [SnappyDataInc/snappydata#1153]
Does smart connector mode on work 'spark on k8s' deployment? Can I still make use of the same example in -

_https://snappydatainc.github.io/snappydata/howto/spark_installation_using_smart_connector/_

Replacing - 
    .master("_**k8s master uri**_")
    // snappydata.connection property enables the application to interact with SnappyData store
    .config("snappydata.connection", "_**snappydata locator ip**_:1527")

Am I on the correct path?

**Comment by jramnara** [comment]
Unfortunately, if you launch a Spark job using spark-submit with k8s as the
master, you cannot use the smart connector to talk to SnappyData. The
connector is only certified for Spark 2.1.1 and the launched driver Pod
with Spark-submit runs Spark 2.2.

So, for now, you can only use Spark JDBC data source API (or just SQL) to
connect to a Snappy cluster.

Of course, you can also launch 'Snappy-job' - which will run entirely
within the Snappy cluster.

Hope that helps.

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://www.snappydata.io/download>

**Comment by thbeh** [comment]
Just to confirm, using Snappy-Job means master is always --master local[*], correct?

**Comment by jramnara** [comment]
You should NOT configure any master. The lead is equivalent to the master.

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://www.snappydata.io/download>

**Comment by thbeh** [comment]
so i saw in this example - https://raw.githubusercontent.com/SnappyDataInc/snappydata/master/examples/src/main/scala/org/apache/spark/examples/snappydata/CreateColumnTable.scala

It still have a call to set master local[*] ,

_def main(args: Array[String]): Unit = {
    parseArgs(args)

    // reducing the log level to minimize the messages on console
    Logger.getLogger("org").setLevel(Level.ERROR)
    Logger.getLogger("akka").setLevel(Level.ERROR)

    val dataDirAbsolutePath: String = createAndGetDataDir

    println("Creating a SnappySession")
    val spark: SparkSession = SparkSession
        .builder
        .appName("CreateColumnTable")
        .master("local[*]")
         // sys-disk-dir attribute specifies the directory where persistent data is saved
        .config("snappydata.store.sys-disk-dir", dataDirAbsolutePath)
        .config("snappydata.store.log-file", dataDirAbsolutePath + "/SnappyDataExample.log")
        .getOrCreate

    val snSession = new SnappySession(spark.sparkContext)

    val pw = new PrintWriter(System.out, true)
    createColumnTableUsingAPI(snSession, pw)
    createColumnTableUsingSQL(snSession, pw)
    createColumnTableInferredSchema(snSession, pw)
    pw.close()
  }_
