### ISSUE TITLE
How can i get external table jdbc url in SnappyData

### ISSUE THREAD

**Issue by yj1018** [SnappyDataInc/snappydata#1204]
previously i created an external table in SnappyData like this:

```
create external table EXT_DIM_CITY
using jdbc options(url 'jdbc:mysql://***:5002/***?user=***&password=***', 
driver 'com.mysql.jdbc.Driver',
dbtable 'dim_city');

```
but now i forget the mysql jdbc url that EXT_DIM_CITY referred to. How can i get the jdbc url from SnappyData

thanks very much!

**Comment by sumwale** [comment]
@yj1018 Sorry for the late reply. Have responded to the StackOverflow question (https://stackoverflow.com/questions/53388666/how-can-i-get-external-table-jdbc-url-in-snappydata) so closing this.
