### ISSUE TITLE
Golang Driver

### ISSUE THREAD

**Issue by wajidp** [SnappyDataInc/snappydata#1296]
Is there a possiblity to connect to snappydata through golang as we require migrate data to sql server.

**Comment by jramnara** [comment]
Can't you simply export your data to CSV or parquet and read from SQLserver ? 'create external table xx using csv options(header 'true') as (select * from xxx)'
Or, you can try generating a Go client using the Thrift API .... https://snappydatainc.github.io/snappydata/programming_guide/multiple_language_binding_using_thrift_protocol/

**Comment by wajidp** [comment]
@jramnara thanks will check
