### ISSUE TITLE
Snappy shell changes part of SQL to UPPERCASE

### ISSUE THREAD

**Issue by foxgarden** [SnappyDataInc/snappydata#1346]
bin/snappy

execute below SQL:
CREATE TABLE `users`(
`id` bigint PRIMARY KEY, 
`name` string)
USING row OPTIONS (PARTITION_BY 'id');

will get:
ERROR 42X01: (SQLState=42X01 Severity=20000) (Server=***/***[1527] Thread=ThriftProcessor-5) Syntax error: The partition column (ID) does not exist in the table's column list.

affected version: 1.1.0

**Comment by jramnara** [comment]
@foxgarden I just tried. Works as expected. 
Can you try invoking `call sys.repair_catalog('false', 'false');` ? Maybe there is an inconsistency in the catalog meta data. See issue described here - https://tibco-computedb.readthedocs.io/en/docv1.1.0/troubleshooting/catalog_inconsistency/

**Comment by sumwale** [comment]
@foxgarden issue is not reproducible on the 1.1.0 release version. If its not the official release version, please paste the output of "snappy version full"

**Comment by foxgarden** [comment]
After repairing meta data it works fine.
Close this issue. Thanks!
