### ISSUE TITLE
Using PreparedStatement and set non-ascii characters into placeholder, query doesn't work

### ISSUE THREAD

**Issue by TeslaCN** [SnappyDataInc/snappydata#1436]
When I using SnappyData's PreparedStatement and set parameter value with non-ASCII (such as Chinese) characters, SnappyData return Nothing. 
Execute SQL "select * from table where value = '粤' " directly works normally and it returns expected data.
But PreparedStatement " select * from table where value = ? " , set value '粤' into the placeholder it doesn't work.(SnappyData return Nothing)(set ascii character works normally)
Should I set something about CharacterEncoding? I found nothing about encoding config when I read the documents.

**Comment by kneeraj** [comment]
Hi @TeslaCN 
Thanks for reporting this. There was some issue in the deserialization of parameters of prepared statements for non-ascii characters. We have fixed this and we are in the process of coming out with the 1.1.1 release in a couple of days which should have this fixed. Will notify you once that is out.
