### ISSUE TITLE
Link to the download/releases is broken

### ISSUE THREAD

**Issue by willschipp** [SnappyDataInc/snappydata#193]
Link in the README.md to the download (tar.gz) (zip) is broken and returns a 404.

Should be the following...

https://github.com/SnappyDataInc/snappydata/releases/download/v0.2-preview/snappydata-0.2.0-PREVIEW.tar.gz 

(difference is the -bin is in 0.1.0 and not in 0.2.0)

**Comment by ashetkar** [comment]
This is fixed on branch-0.x-preview, thanks.
