### ISSUE TITLE
Aws EMR /tmp/hive permission Error

### ISSUE THREAD

**Issue by yusufcangurkan** [SnappyDataInc/snappydata#202]
--  USING parquet OPTIONS(path '../../quickstart/data/airlineParquetData_2007-15');

----- CREATE COLUMN TABLE -----
----- Airline row count is small so we use 11 buckets (i.e. 11 partitions) -----
CREATE TABLE AIRLINE USING column OPTIONS(buckets '11') AS (
  SELECT Year AS Year_, Month AS Month_ , DayOfMonth,
    DayOfWeek, DepTime, CRSDepTime, ArrTime, CRSArrTime,
    UniqueCarrier, FlightNum, TailNum, ActualElapsedTime,
    CRSElapsedTime, AirTime, ArrDelay, DepDelay, Origin,
    Dest, Distance, TaxiIn, TaxiOut, Cancelled, CancellationCode,
    Diverted, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay,
    LateAircraftDelay, ArrDelaySlot
    FROM STAGING_AIRLINE);
ERROR 38000: (SQLState=38000 Severity=-1) (Server=localhost[1528],Thread[DRDAConnThread_38,5,gemfirexd.daemons]) The exception 'com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: ip-10-78-5-244(29531)<v1>:46672, caused by java.lang.RuntimeException: java.lang.RuntimeException: The root scratch dir: /tmp/hive on HDFS should be writable. Current permissions are: rwx------' was thrown while evaluating an expression.

---

_Even if i made change as -> hdfs dfs -chmod 777 /tmp/hive 
it did not work._

**Comment by sumwale** [comment]
@yusufcangurkan What are the permissions on /tmp? "ls -ld /tmp" should show: drwxrwxrwt

**Comment by yusufcangurkan** [comment]
@sumwale 

Now it shows: lrwxrwxrwx 1 root root 8 Mar 21 09:01 /tmp -> /mnt/tmp

But it's about hdfs not the folder in root.

**Comment by sumwale** [comment]
I think the message is misleading because this is just a local scratch directory used. Can you check the same for /mnt/tmp?

**Comment by yusufcangurkan** [comment]
0 drwx------  4 hive     hive       140 Mar 21 09:15 hive

it's like that in /mnt/tmp

What should i do now? @sumwale

**Comment by sumwale** [comment]
Sorry could you check "ls -ld /mnt/tmp"?

First thing would be to delete the /mnt/tmp/hive directory.

**Comment by yusufcangurkan** [comment]
Ok @sumwale,  your solution solved my problem. 

Now, when i added 
libraryDependencies += "io.snappydata" % "snappy-core_2.10" % "0.2.0-PREVIEW"

to build.sbt

and it gives error below:

_scala> val snc = org.apache.spark.sql.SnappyContext(sc)
16/03/21 16:28:49 INFO ToolsCallbackInit: toolsCallback initialized
snc: org.apache.spark.sql.SnappyContext = org.apache.spark.sql.SnappyContext@46a1328f

scala> val results3 = snc.sql("show tables")
java.lang.NoSuchMethodError: org.apache.spark.sql.SnappyContext.sqlParser()Lorg/apache/spark/sql/SparkSQLParser;_

**Comment by sumwale** [comment]
@yusufcangurkan sorry missed last comment. Do you also have apache spark dependencies directly or indirectly in build.sbt? This issue indicates that it is trying to use the stock upstream spark instead of the additions snappydata ships with. We are working on ability to run against stock spark but its not in the code yet.

Also you can check with "0.2.1-PREVIEW"

**Comment by sumwale** [comment]
The hive directory location (not used by SnappyData but created nevertheless by hive metastore initialization) was changed to working directory by default in https://github.com/SnappyDataInc/snappydata/pull/809 to avoid user permission issues with /tmp/hive. One other issue with a rare concurrent initialization race leading to directory create failure is being tracked in [SNAP-1986](https://jira.snappydata.io/browse/SNAP-1986) so closing this issue.
