### ISSUE TITLE
is snappydata production ready

### ISSUE THREAD

**Issue by thbeh** [SnappyDataInc/snappydata#289]
Hi, i have been looking at snappydata for last couple of days and technically I understand how it works but I would appreciate if I could be pointed to some understanding on how it will fit in a lambda architecture (which I feel snappydata should be at the speed layer). Secondly, i understand OLAP from the conventionally ways of Essbase and Oracle  but I just can't put snappydata's OLAP queries compared to Essabse/Oracle. 
Finally I would like to put up a showcase on data lake warehouse and would like to know whether is snappydata production ready? Thanks in advance.

**Comment by sudsmenon** [comment]
Hi,

SnappyData absolutely fits the speed layer and through its transparent support for Sparksql and approximate querying support offers olap capabilities as well

It is built on two solid platforms ( Spark and GemFire ) and we are working on a GA release in August. The .4 release which is up there on github is stable and has been used in POCS and benchmarks.

Can you drop me a note at smenon at SnappyData dot io and we can discuss how we can help you with the data lake showcase

Suds
