### ISSUE TITLE
Connect to repository.snappydata.io:8089 [repository.snappydata.io/52.34.95.228] failed: Operation timed out

### ISSUE THREAD

**Issue by birlinn** [SnappyDataInc/snappydata#290]
When trying to build the latest sources, i get this error:

snappydata$ ./gradlew product
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/xxxxx/projects/snappydata/build.gradle' line: 301
- What went wrong:
  Could not resolve all dependencies for configuration ':snappy-examples_2.10:testRuntime'.
  
  > Could not resolve io.snappydata:snappy-aqp_2.10:0.4.0-PREVIEW.
  > Required by:
  >     io.snappydata:snappy-examples_2.10:0.4.0-PREVIEW
  > Could not resolve io.snappydata:snappy-aqp_2.10:0.4.0-PREVIEW.
  > Could not get resource 'http://repository.snappydata.io:8089/repository/internal/io/snappydata/snappy-aqp_2.10/0.4.0-PREVIEW/snappy-aqp_2.10-0.4.0-PREVIEW.pom'.
  >      > Could not GET 'http://repository.snappydata.io:8089/repository/internal/io/snappydata/snappy-aqp_2.10/0.4.0-PREVIEW/snappy-aqp_2.10-0.4.0-PREVIEW.pom'.
  >         > Connect to repository.snappydata.io:8089 [repository.snappydata.io/52.34.95.228] failed: Operation timed out
  > Could not resolve io.snappydata:snappy-aqp_2.10:0.4.0-PREVIEW.
  > Could not get resource 'http://repository.snappydata.io:8089/repository/snapshots/io/snappydata/snappy-aqp_2.10/0.4.0-PREVIEW/snappy-aqp_2.10-0.4.0-PREVIEW.pom'.
  >      > Could not GET 'http://repository.snappydata.io:8089/repository/snapshots/io/snappydata/snappy-aqp_2.10/0.4.0-PREVIEW/snappy-aqp_2.10-0.4.0-PREVIEW.pom'.
  >         > Connect to repository.snappydata.io:8089 [repository.snappydata.io/52.34.95.228] failed: Operation timed out
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by ashetkar** [comment]
@birlinn 
Are you connected to the internet? The error message indicates that it could not reach repository.snappydata.io:8089, where the AQP artifacts are hosted. These artifacts may be needed for running the examples.

**Comment by birlinn** [comment]
yes, my network connection seems fine, except that there's a problem connecting to repository.snappydata.io:8089

**Comment by birlinn** [comment]
$ dig repository.snappydata.io

; <<>> DiG 9.8.3-P1 <<>> repository.snappydata.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52064
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;repository.snappydata.io.	IN	A

;; ANSWER SECTION:
repository.snappydata.io. 3600	IN	CNAME	ec2-52-34-95-228.us-west-2.compute.amazonaws.com.
ec2-52-34-95-228.us-west-2.compute.amazonaws.com. 78963	IN A 52.34.95.228

;; Query time: 130 msec
;; SERVER: 10.66.1.2#53(10.66.1.2)
;; WHEN: Tue Jun 28 14:07:23 2016
;; MSG SIZE  rcvd: 120

$ ping 52.34.95.228
PING 52.34.95.228 (52.34.95.228): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
^C
--- 52.34.95.228 ping statistics ---
11 packets transmitted, 0 packets received, 100.0% packet loss

**Comment by ashetkar** [comment]
Are you using any proxy or behind a firewall? Confirmed that repository.snappydata.io:8089 is up and running.
Are you able to telnet the hostname port? Something like:
```
telnet 52.34.95.228 8089
Trying 52.34.95.228...
Connected to 52.34.95.228.
Escape character is '^]'.
```

**Comment by birlinn** [comment]
no proxy, no firewall, everything else seems fine...

$ telnet 52.34.95.228 8089
Trying 52.34.95.228...
telnet: connect to address 52.34.95.228: Operation timed out
telnet: Unable to connect to remote host

i assume it's some kind of local/temporary network disturbance specific to my current location

will try again later: thanks for trying to help

**Comment by ashetkar** [comment]
@birlinn Any luck with it later?

**Comment by birlinn** [comment]
build still failing

same problem

tried on 3 different networks

not sure what else to try

**Comment by jramnara** [comment]
@birlinn Could you just try the [binary](https://github.com/SnappyDataInc/snappydata/releases/tag/v0.4-preview) until this gets figured out?

**Comment by birlinn** [comment]
will do

thanks

**Comment by sumwale** [comment]
Server hosting the jar has been tested to be running fine. Open if still reproducible. @birlinn

**Comment by doflink** [comment]
I have the same problem. 
`Connection to http://repository.snappydata.io:8089 refused`

**Comment by ymahajan** [comment]
Are you getting the error for aqp repo?

Try changing AQP's build.gradle as following to use default port and see if it works - 

-        repository(url: 'http://repository.snappydata.io:8089/repository/internal/') {
+        repository(url: 'http://repository.snappydata.io/repository/internal/') {
            authentication(userName: archivaUsername, password: archivaPassword)
          }
 -        snapshotRepository(url: 'http://repository.snappydata.io:8089/repository/snapshots/') {
 +        snapshotRepository(url: 'http://repository.snappydata.io/repository/snapshots/') {

**Comment by ymahajan** [comment]
Or use the binary for now https://github.com/SnappyDataInc/snappydata/releases/tag/v0.9
