### ISSUE TITLE
question

### ISSUE THREAD

**Issue by thbeh** [SnappyDataInc/snappydata#292]
I notice in snappydata docs, we can actually have multiple nodes for locators, leads and servers. I saw some config example in configuration section. My question is do we need to deploy the _**snappydata-0.4.0-PREVIEW-bin.tar.gz**_ onto each node. Is there some documentation on deploying on multiple nodes?

**Comment by hbhanawat** [comment]
Yes. Alternatively, you can install it on NFS location which is accessible
on all machines.
