### ISSUE TITLE
Could not connect to SnappyData Network Server on host 127.0.0.1, port 1527: Connection refused

### ISSUE THREAD

**Issue by thbeh** [SnappyDataInc/snappydata#305]
Any reasons I am getting this (bold) when I start locator using hostname -

16/07/12 10:13:02.504 UTC serverConnector<tid=0xd> INFO snappystore: Region /_DDL_STMTS_META_REGION recovered from the local disk. Old persistent ID: /172.17.0.2:/./datadictionary created at timestamp 1468318269506 version 0 diskStoreId a1c4c7a6-f1e8-404d-847d-09eb330bc8c3 name , new persistent ID /172.17.0.2:/./datadictionary created at timestamp 1468318382503 version 0 diskStoreId a1c4c7a6-f1e8-404d-847d-09eb330bc8c3 name 
16/07/12 10:13:03.159 UTC serverConnector<tid=0xd> INFO snappystore: acquired dd read lock during post create
16/07/12 10:13:03.219 UTC serverConnector<tid=0xd> INFO snappystore: FabricDatabase: waiting for index loading from GFXD-DEFAULT-DISKSTORE
16/07/12 10:13:03.220 UTC serverConnector<tid=0xd> INFO snappystore: FabricDatabase: Index loading completed for GFXD-DEFAULT-DISKSTORE in 0 ms
16/07/12 10:13:03.223 UTC Idle OplogCompactor<tid=0x37> INFO snappystore: Oplog::recoverValuesIfNeeded: recovering values from oplog#1
16/07/12 10:13:03.705 UTC serverConnector<tid=0xd> INFO snappystore: FabricDatabase: initial DDL replay completed.
**16/07/12 10:13:03.706 UTC serverConnector<tid=0xd> INFO snappystore: FabricDatabase: Authentication recheck successful._16/07/12 10:13:03.712 UTC main<tid=0x1> INFO snappystore: TraceFabricServiceBoot: Starting DRDA server on: localhost/127.0.0.1[1527]
SnappyData Network Server - 10.4.2.0 beta - (1) started and ready to accept connections on port 1527 at 2016/07/12 10:13:03.765 UTC 
Could not connect to SnappyData Network Server on host 127.0.0.1, port 1527: Connection refused
16/07/12 10:13:03.768 UTC gemfirexd.NetworkServerStarter<tid=0x3d> INFO snappystore: SnappyData Network Server - 10.4.2.0 beta - (1) started and ready to accept connections on port 1527 at 2016/07/12 10:13:03.765 UTC**_ 
16/07/12 10:13:03.770 UTC main<tid=0x1> INFO snappystore: Could not connect to SnappyData Network Server on host 127.0.0.1, port 1527: Connection refused
16/07/12 10:13:03.868 UTC main<tid=0x1> INFO snappystore: TraceFabricServiceBoot: Started DRDA server on: localhost/127.0.0.1[1527]

**Comment by jramnara** [comment]
hmm! maybe we are trying to connect to the IP address as the hostname first. Everything started  just fine?

**Comment by thbeh** [comment]
Everything seems working so far.

**Comment by sumwale** [comment]
Just looked at this old issue. The log about inability to connect internally is normal (inherited from Derby) where it triggers startup of the DRDA server (though perhaps an annoyance).
