### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by thbeh** [SnappyDataInc/snappydata#327]
While snappydata uses rowstore for row table and Spark dataframe for column table, does snappydata allows data to persists to disk  and allowing to query from both memory and disk? 

Thanks

**Comment by jramnara** [comment]
Yes, any Snappy table (Column or Row) can be fully persistent on disk also. And, the data can overflow to disk too. Queries can be executed on any of these tables. 

But, do also note that a column table isn't a Spark DataFrame. Any Spark RDD/DataFrame is merely metadata (it simply knows how to acquire the data in a partitioned and parallel manner) but isn't really managing the data in-memory unless you explicitly cache/persist the data. Think of a Dataframe more like a "view" in a traditional database. 
What we do is simply use the same columnar data format spark internally uses to manage data in Snappy's column tables. But, the container (storage layer) itself is quite different - you can replicate data sets to provide HA, using different eviction models, etc. 
All Tables in Snappy are also exposed as Spark DataFrames (i.e. row , column, stratified Samples,..)

**Comment by thbeh** [comment]
So for data overflow, do you use EVICTION_BY or PERSISTENT syntax?

**Comment by jramnara** [comment]
Column tables are configured to overflow, by default. Uses heap based
eviction (i.e. EVICTION_BY lruheappercent).

I think, you need to set the --heap-size option in your 'conf/servers'
(see config
page <http://snappydatainc.github.io/snappydata/configuration/>)

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://github.com/SnappyDataInc/snappydata>

**Comment by thbeh** [comment]
Ok. Noted with thanks.
