### ISSUE TITLE
Invalid token NULL for executePrepared

### ISSUE THREAD

**Issue by fire** [SnappyDataInc/snappydata#393]
When writing an elixir driver using the thrift protocol I noticed errors of an invalid token NULL for executePrepared. https://github.com/SnappyDataInc/snappy-store/blob/6e18e745094849f72739bbf924a64b777c9fcba7/gemfirexd/core/src/main/java/io/snappydata/thrift/server/SnappyDataServiceImpl.java#L2345

Looking at the code I noticed code of this pattern. `stmtHolder.getConnectionHolder().equals(token)` 
  https://github.com/SnappyDataInc/snappy-store/blob/6e18e745094849f72739bbf924a64b777c9fcba7/gemfirexd/core/src/main/java/io/snappydata/thrift/server/SnappyDataServiceImpl.java#L413

A Connection holder is not the same type as a token.

**Comment by sumwale** [comment]
Hi @fire 

The token must be passed back from what was returned by openConnection call in ConnectionProperties in every call that requires a token argument.

The name "equals" is misleading though it does check equality with token: https://github.com/SnappyDataInc/snappy-store/blob/6e18e745094849f72739bbf924a64b777c9fcba7/gemfirexd/core/src/main/java/io/snappydata/thrift/server/ConnectionHolder.java#L490  Will rename to "sameToken"

**Comment by sumwale** [comment]
Method has now been renamed to "sameToken" (https://github.com/SnappyDataInc/snappy-store/commit/c8f382f712e13eb0b22e19dc5073581e872b0601).

@fire let me know if there was any issue after passing proper token as received in openConnection call. Else will close this issue if its fine.

**Comment by fire** [comment]
I'll check back.

**Comment by sumwale** [comment]
This should be working now as mentioned above, so closing @fire
