### ISSUE TITLE
gradle idea error

### ISSUE THREAD

**Issue by weijietong** [SnappyDataInc/snappydata#395]
running the command gradle idea on the v0.6 tag source code occurs error,the message is as follow:

> FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/twj/code/snappydata/build.gradle' line: 63
- What went wrong:
  A problem occurred evaluating root project 'snappydata_2.11'.
  No such property: classfier for class: org.gradle.api.internal.project.DefaultProject_Decorated

**Comment by sumwale** [comment]
Hi @weijietong 

Are you trying to build from within Intellij IDEA? Can you tell the version? Please use gradle wrapper when importing in IDEA as a gradle project. Also see other notes for IDEA here: https://github.com/SnappyDataInc/snappydata/blob/master/docs/build-instructions.md

For the latest 2016.X versions, also uncheck "separate module per source set" option in the import.

**Comment by weijietong** [comment]
IntelliJ IDEA 2016.1.3
Build #IC-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
This is my idea version. Even using gradlew idea  command line in the console ,also the same error message.When I import the project using IDEA ,also the same error msg.

**Comment by sumwale** [comment]
The notes on IDEA are now in install.md https://github.com/SnappyDataInc/snappydata/blob/master/docs/install.md#building-from-source

IDEA builds have been working for long (with "separate module per source set") so not sure what can be done about this old reported. Please check back and reopen if it is still an issue with latest master or branch-0.8 @weijietong
