### ISSUE TITLE
is there exist demos to load snappy hdfsstore format(hop) by spark

### ISSUE THREAD

**Issue by hzxjtx** [SnappyDataInc/snappydata#520]
hi
     I use snappy hdfsstore to insert some data to hdfs, i get the data format as follows"
-rw-r--r--   3 root root          0 2017-03-03 10:10 /mnt/benchmark/hstore.dat/APP_X2/9/9-1488507015508-68384.hop.exp
-rw-r--r--   3 root root       5509 2017-03-03 10:10 /mnt/benchmark/hstore.dat/APP_X2/9/9-1488507016377-68385.hop
-rw-r--r--   3 root root          0 2017-03-03 10:10 /mnt/benchmark/hstore.dat/APP_X2/9/9-1488507016377-68385.hop.exp

how can i use spark to load this format data, thanks

**Comment by sumwale** [comment]
@hbhanawat we have hadoop API readers for this but do you know if it is possible to load it in Spark? I suppose one could write a DataSource for it but is there a direct way?

**Comment by hbhanawat** [comment]
@hzxjtx @sumwale 
For accessing row store data persisted on HDFS using map reduce, RowInputFormat and RowOutputFormat  are used. See here http://rowstore.docs.snappydata.io/docs/disk_storage/persist-hdfs-topics.html#topic_358EB80C30F24D9A8BEAD382C30FC0DA 

Same formatters can be used to access data via spark. We had done it some time back on an older version of Spark.

**Comment by sumwale** [comment]
@hbhanawat 

> Same formatters can be used to access data via spark.

You mean with a custom RDD implementation, or is there some direct way in Spark?

**Comment by hbhanawat** [comment]
No there is an implementation already available. Checkout SparkContext.hadoopRDD. Haven't tried that in a while though.

**Comment by sumwale** [comment]
@hzxjtx Could you get Spark's HadoopRDD/NewHadoopRDD to work? Closing this issue since the rowstore HDFS persistence is not supported and writing table data to HDFS can be done using the normal Dataset APIs. Future support for direct persistence to HDFS will be provided and reported in #400
