### ISSUE TITLE
WordPress?

### ISSUE THREAD

**Issue by LZL0** [SnappyDataInc/snappydata#528]
Guys, I really love what you are creating. Although I have no advanced understanding of it. How can SnappyData be integrated with Content Management Systems like WordPress? Can MySQL be replaced by SnappyData? Could you provide some links about it (if available)? I have not found anything particular under this github repo or on the site under the Resources tab about it.

Sorry for writing about this under the issues section.
Thank you in advance for your kind answers.

**Comment by jramnara** [comment]
Unlikely, it will work. If WordPress is specifically designed for MySQL it
is likely to use its SQL dialect which won't necessarily work with
SnappyData.

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://github.com/SnappyDataInc/snappydata>

**Comment by piercelamb** [comment]
Just to expand, SnappyData is targeted at use cases that require streaming, high ingestion rates, concurrent, low latency, OLAP or OLTP queries and more. If you're looking for a backend for a CMS, it is unlikely that SnappyData is the right sort of database for the job. Classic RDBMS like MySQL or Postgres or Document DBs like Mongo are better suited. That said, if you have a use case like the streaming case mentioned above and are looking to serve queries from a web interface, for example, SnappyData would be a good fit.

**Comment by LZL0** [comment]
thank you for your answers!
