### ISSUE TITLE
snappydata lost data?

### ISSUE THREAD

**Issue by hzxjtx** [SnappyDataInc/snappydata#530]
hi
env: 5 machines using embeded cluster mode, snappy0.7

1) I create a column table as follows:(the table is about 20g)
    val buckets = "256"
    val props1 = Map(("PARTITION_BY" -> "uid"), ("BUCKETS" -> buckets), ("PERSISTENT" -> "SYNCHRONOUS"), ("EVICTION_BY" -> "LRUHEAPPERCENT"))
    snSession.createTable(tableName, "column", df.schema, props1)
   after creation, then insert about 20g data to the table(pt_sum_tb)

2) use 1) created table, to create anthor table
snappy> create table row_PT_SUM_TB using row as (select * from PT_SUM_TB);
0 rows inserted/updated/deleted

finally found  row_pt_sum_tb has many rows but pt_sum_tb table all data has gone....
what happened??? can some one tell me

**Comment by SachinJanani** [comment]
Hi @hzxjtx 
We have tested this scenario with less data and its working fine.Can you check status of server process?

**Comment by hzxjtx** [comment]
@SachinJanani 
all the dataserver is running, and all components on dashboard are ok.
i test small datasets, this is error not exist

**Comment by hzxjtx** [comment]
@SachinJanani 

I used tpc-h 1g dataset for test: the question is still.
In 1G tpc-h datasets, lineItem records count is: 6001215, I use the command "creat table copy_col_lineitem using column as(select * from lineitem)" to create anthor table, i found the fact than: the source table lineItem records count change from 6001215 to 2000384, and the dest table copy_col_lineitem is 3081025. both the two table records count is real data size. can you give some information?

**Comment by SachinJanani** [comment]
@hzxjtx 
We tried the scenario that you mentioned again with tpch 1g dataset but was not able to reproduce this issue.Can you please provide the configuration files ,DDL scripts and logs files.So that we can investigate further.

**Comment by SachinJanani** [comment]
@hzxjtx 
Sorry we have also reproduced this issue will fix it ASAP and notify you

**Comment by SachinJanani** [comment]
@hzxjtx 
This issue was caused due to default EVICTACTION which we are setting to local-destroy please set EVICTACVTION to overflow.Following is the syntax of specifying EVICTACTION to OVERFLOW:

`create table lineitem_col USING column options(PARTITION_BY 'L_ORDERKEY', BUCKETS '256', PERSISTENT 'SYNCHRONOUS', EVICTION_BY 'LRUHEAPPERCENT',` **OVERFLOW 'true'** `) ;`

**Comment by sumwale** [comment]
@SachinJanani Is there a JIRA issue to track this? Default eviction action should have been overflow for column tables.

**Comment by sumwale** [comment]
@hzxjtx The default eviction action is being tracked in JIRA issue [SNAP-1501](https://jira.snappydata.io/browse/SNAP-1501?jql=text%20~%20%22evictaction%22). For now explicitly setting OVERFLOW as the action for replicated row tables is required. Column tables already default to OVERFLOW as the eviction action by default now.
