### ISSUE TITLE
snappy-data examples not working in rowstore mode

### ISSUE THREAD

**Issue by Richard-bizruntime** [SnappyDataInc/snappydata#531]
I am start to learning the snappy-data,and running the snappy-data examples as per the Documentation, while Start in snappy-data server like
$SNAPPY_HOME$ ./sbin/snappy-start-all.sh
./bin/run-example snappydata.JDBCExample
comment ,the snappy-data example are executing, at the same time when using snappy-data row-store its not working while starting snappy-data a like
" $SNAPPY_HOME$ ./sbin/./sbin/snappy-start-all.sh rowstore "
./bin/run-example snappydata.JDBCExample
like that i will execute the comment. could you any one knows how to run snappy examples in row-store, please share me, Thank you.. for the Reference snappy-data rows-tore Documentation "http://rowstore.docs.snappydata.io/docs/getting_started/tutorial_chapter_intro.html"

then i need to read data from csv file and insert in to Snappy table, as per the documentation snappydata.JDBCExample we can connect the snappy table and create the table, i dont know how to read csv file, and insert into the table, anyone know how to store the csv in the table, please share me , thank you.. 

StackOverflow:
http://stackoverflow.com/questions/42714577/snappy-data-examples-not-working-in-rowstore-mode/42715366?noredirect=1#comment72551858_42715366

**Comment by sumwale** [comment]
@Richard-bizruntime welcome.

The pure rowstore mode is intended mostly for users of the old [GemFireXD](http://gemfirexd.docs.pivotal.io/) product line for transitioning to SnappyData. That works nearly identical to GemFireXD as purely a JDBC/ODBC/SQL data-store with no integration with Spark or other of the SnappyData features, so most of those examples will not work. Unless you have special requirements I will suggest using the SnappyData product in normal mode which has full integration with Spark and provides for row tables via "CREATE TABLE ... USING ROW ..." that can be updated/deleted just like in pure rowstore mode.

For the specific question about import from CSV, the way to import is using the old [procedures](http://rowstore.docs.snappydata.io/docs/reference/system_procedures/derby/rrefimportproc_ex.html#rrefimportproc) as documented in [rowstore docs](http://rowstore.docs.snappydata.io/docs/tools/topics/ddlutils.html). However, as mentioned this is not the recommended route and instead you should run SnappyData in normal mode creating ROW tables if required.

**Comment by Richard-bizruntime** [comment]
@sumwale Thank you, But in the normal Snappydata will support the HDFS persistance mode.i need to store oveflow data in the HDFS storage.

**Comment by sumwale** [comment]
@Richard-bizruntime as of now HDFS persistence in SnappyData has to be done explicitly via normal Spark APIs (DataFrameWriter). We are tracking the need to persist/read from HDFS as an inbuilt feature. For now the options are to either use a) SnappyData with explicit HDFS persistence, b) or use the old rowstore product but with old APIs to load data etc

**Comment by sumwale** [comment]
@Richard-bizruntime As mentioned, explicit Spark Dataset APIs can be used to persist a snapshot of data (iterators provide partition-wise snapshot isolation by default now) to HDFS. Direct persistence of column tables to HDFS will be added in near future and being tracked in #400
