### ISSUE TITLE
distinct function Nested queries problem

### ISSUE THREAD

**Issue by junkeyjava** [SnappyDataInc/snappydata#534]
distinct function Nested queries problem  have a prolem，Whether it is bug？
I have a table.
CREATE TABLE app.yes_with(
  device_id  VARCHAR(200) , 
  device_brand  VARCHAR(200), 
  device_model  VARCHAR(200), 
  system_version  VARCHAR(200), 
  system_name  VARCHAR(200) ,
  oem_system_version  VARCHAR(200) , 
  oem_system_name  VARCHAR(200) ,
  sample_app_version  VARCHAR(200), 
  app_key  VARCHAR(200), 
  app_channel  VARCHAR(200) , 
  sample_user_id  VARCHAR(200) , 
  sample_package_name  VARCHAR(200) , 
  sample_app_name  VARCHAR(200) , 
  sdk_version  VARCHAR(200) , 
  api_level  VARCHAR(200), 
  mobile_corporation  VARCHAR(200) , 
  phone_num  VARCHAR(200) , 
  ip  VARCHAR(200) , 
  mac_address  VARCHAR(200) , 
  page_url  VARCHAR(200) , 
  page_title  VARCHAR(200), 
  package_name  VARCHAR(200) , 
  page_tag  VARCHAR(200) ,
  open_time bigint , 
  close_time bigint , 
  from_page_name  VARCHAR(200), 
  to_page_name  VARCHAR(200),
 day  VARCHAR(200) , 
 page  VARCHAR(200) )
  USING COLUMN OPTIONS (PERSISTENT 'asynchronous',PARTITION_BY  '**device_id**',BUCKETS '800');

The following statement is correct：
select a.device_brand,count(distinct a.**device_model**) from no_with a,yes_with b where a.device_brand=b.device_brand group by a.device_brand limit 10;

The following sentence error：
select sdk_version, count(distinct **device_id**) from (select sdk_version,device_id from  APP.YES_WITH group by sdk_version,device_id) a group by sdk_version ;

	at Remote Member 'isunode011(19649)<v16>:11310' in org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:133)
	at Remote Member 'isunode011(19649)<v16>:11310' in org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:114)
	at Remote Member 'isunode011(19649)<v16>:11310' in org.apache.spark.sql.execution.aggregate.SnappyHashAggregateExec.doExecute(SnappyHashAggregateExec.scala:212)
	at Remote Member 'isunode011(19649)<v16>:11310' in org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:115)
	at Remote Member 'isunode011(19649)<v16>:11310' in org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:115)
	at Remote Member 'isunode011(19649)<v16>:11310' in org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:136)
Caused by: java.lang.StackOverflowError

**Comment by junkeyjava** [comment]
use version 0.8

**Comment by sumwale** [comment]
@junkeyjava Thanks, looking into this. The code generation is failing and there is (deliberately) no fallback path in SnappyHashAggregateExec.

Some background: there seems to be a lingering problem with dictionary optimization in some code generation paths. It uses the dictionary index to do the grouping where possible, and avoids materializing the value (if groupBy map already has the value against that index). So the respective variables having values are not declared at top-level rather materialized inside after the lookup. However, for certain joins etc it had to be done outside due to issues like above. This seems to be some new code path where the same issue is being seen.

**Comment by sumwale** [comment]
@junkeyjava Similar issue being tracked here: https://jira.snappydata.io/browse/SNAP-1459.

However, this one is a slight variation which is being tracked separately.

**Comment by sumwale** [comment]
@junkeyjava This issue turns out to be a completely different one from SNAP-1459 and not "a slight variation". PR has been created and will be merged to master and 0.8 branch soon: https://github.com/SnappyDataInc/snappydata/pull/569

**Comment by sumwale** [comment]
JIRA issue: https://jira.snappydata.io/browse/SNAP-1480
