### ISSUE TITLE
jdbc with column store

### ISSUE THREAD

**Issue by thbeh** [SnappyDataInc/snappydata#536]
Hi, can I use jdbc with column store with the following - 

url = jdbc:snappydata://locator1:1527/
username = app
password = app
driver class = com.pivotal.gemfirexd.jdbc.ClientDriver

**Comment by jramnara** [comment]
yes, to access any table  ... column or row. If using 0.8 release, switch to Driver class - io.snappydata.jdbc.ClientDriver

**Comment by thbeh** [comment]
I got this when trying to connect using 0.8 release -
ERROR: An error occurred while trying to make a connection to 
the database:  

JDBC URL: jdbc:snappydata://192.168.20.208:1527/

(SQLState=40XD0 Severity=30000) ([192.168.100.88[1528]]) 
Container has been closed or has moved from 
'192.168.20.208[1527]' {failed after trying all available 
servers: [192.168.100.88[1528], snappydata/0.0.0.0[1527], 
192.168.20.208[1527]]}. 

The reason for 2 IP is because I am running in a VM environment, 100.88 is the internal IP and 20.208 is the external IP.

**Comment by sumwale** [comment]
@thbeh 

You can force the servers/locators to send custom IPs/hostnames to client driver using "hostname-for-clients" property (e.g. add -J-Dgemfirexd.hostname-for-clients=192.168.20.208) in conf/servers and conf/locators.

Or you can disable load-balancing in the client jdbc:snappydata://192.168.20.208:1527/;load-balance=false but that will miss out on the load-balancing and failover capabilities.

**Comment by sumwale** [comment]
@thbeh This has been tested to work fine with "hostname-for-clients" property in locators and servers. That is add in conf/locators, conf/servers: ... -hostname-for-clients=192.168.20.208
