### ISSUE TITLE
Column Table not  execute UPDATE/DELETE  operation 

### ISSUE THREAD

**Issue by junkeyjava** [SnappyDataInc/snappydata#537]
snappy> CREATE TABLE app.tabletest(
>   device_id  VARCHAR(200) , 
>   device_brand  VARCHAR(200))
>   USING COLUMN   OPTIONS (PARTITION_BY  'device_id', BUCKETS '800');
0 rows inserted/updated/deleted
snappy> insert into app.tabletest values('12','haha');
1 row inserted/updated/deleted
snappy> delete from  app.tabletest where device_id='12';
ERROR 42Y62: (SQLState=42Y62 Severity=20000) (Server=isunode007/192.168.220.141[1527] Thread=pool-3-thread-32) 'UPDATE/DELETE (Column Table) ' is not allowed on 'APP.TABLETEST' because it is a view.
Caused by: ServerException: Server STACK: java.sql.SQLSyntaxErrorException(42Y62): 'UPDATE/DELETE (Column Table) ' is not allowed on 'APP.TABLETEST' because it is a view.
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:480)
	at com.pivotal.gemfirexd.internal.impl.sql.GenericStatement.prepMinion(GenericStatement.java:805)
	at com.pivotal.gemfirexd.internal.impl.sql.GenericStatement.prepare(GenericStatement.java:219)
	at com.pivotal.gemfirexd.internal.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(GenericLanguageConnectionContext.java:1010)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1205)

**Comment by rishitesh** [comment]
We don not support Column table update & deletes yet. This feature is
planned for next release.

Regards,
Rishitesh Mishra,
SnappyData . (http://www.snappydata.io/)

https://in.linkedin.com/in/rishiteshmishra

**Comment by erjunzhang** [comment]
@rishitesh now  we want to  delete column table  some day data  , have some way   to do

**Comment by erjunzhang** [comment]
@rishitesh now  we want to  delete column table  some day data  , have some way   to do

**Comment by junkeyjava** [comment]
Whether the new branch has been resolved ， Column table not support update & deletes problem?If the source code has been submitted to the community, we can compile it ourselves。please give me a url。

**Comment by piercelamb** [comment]
@erjunzhang Column tables do not currently support updates, but that feature is planned for the next release.

@junkeyjava I'm not sure if the aforementioned feature is in the master branch, but you can always download the latest source code and compile it yourself. Check out these instructions: http://snappydatainc.github.io/snappydata/install/#building-from-source

**Comment by sumwale** [comment]
@junkeyjava update/delete support for column tables is an active work in progress and is being tracked here: https://jira.snappydata.io/browse/SNAP-1387. One PR for it is already up and remaining completing the work will be there in a week or two.

**Comment by sumwale** [comment]
SNAP-1389 is now on master and provides update, delete support in column tables so closing this.

**Comment by sumwale** [comment]
@junkeyjava check current master to test update, delete support. Will be in 1.0 release. Currently only via session.sql("update ...") SQL strings. Support via JDBC/ODBC will be added shortly. Clean API support will be added in 1.1 timeframe.
