### ISSUE TITLE
Undefined function: 'DSID'

### ISSUE THREAD

**Issue by erjunzhang** [SnappyDataInc/snappydata#541]
> SELECT DISTINCT dsid() FROM app.ODS_DEV_DEVICE_INFO_D0301;
ERROR 38000: (SQLState=38000 Severity=20000) (Server=isunode002/192.168.220.136[1528] Thread=pool-3-thread-32) The exception 'Undefined function: 'DSID'. This function is neither a registered temporary function nor a permanent function registered in the database 'DEFAULT'.;' was thrown while evaluating an expression.

i want to use dsid() function,but not support 

how  return the string form of the unique distributed member process identity in the snappydata cluster. 

thanks

**Comment by kneeraj** [comment]
Please use this query it will work:

select distinct dsid() from <_tablename_> -- GEMFIREXD-PROPERTIES executionEngine=Store\n;

If you just want to see the distinct members in the distributed system you can use this:

Please note dsid() function has full support with row tables and of course with above query hint. For column tables there could be limitations. For example finding out counts of rows grouped by members using dsid() function will ony return those rows which have not been converted into columnar format.
Please let us know if you need more information here.

**Comment by hbhanawat** [comment]
If you are just trying to find out members in a cluster, in addition to what @kneeraj  says, you can also run the following query on the snappy SQL shell.

select * from sys.members

**Comment by erjunzhang** [comment]
@kneeraj  i want to query some column table how the data distribution in  the distributed system.

i kown row table is no problem

app.ODS_DEV_DEVICE_INFO_D0301 is column table  ,but the query results are empty


snappy> SELECT DISTINCT dsid() FROM app.ODS_DEV_DEVICE_INFO_D0301 -- GEMFIREXD-PROPERTIES executionEngine=Store\n;
_c0                                                                                                                             
--------------------------------------------------------------------------------------------------------------------------------

0 rows selected

**Comment by kneeraj** [comment]
@erjunzhang -- yes this is one of the limitation for column tables now. All your data has got converted into the optimized column format which is stored in a different internal table and that is why you are getting empty results. So had some of the rows were still to be converted to columnar format you would have got data distribution of only those rows with this query. Try inserting few rows and you can see that.
But obviously you would want to see actual data distribution of the entire table irrespective of where the product is storing things internally.
Let me try some queries on internal tables and see if I can provide you with a query which solves your purpose for now. But a cleaner solution is to make this query as is. I mean whatever you tried should work. We will need some work on this and we will introduce this at some future point.

**Comment by kneeraj** [comment]
Use this query for now:

select numrows, dsid() from SNAPPYSYS_INTERNAL.APP__<_tablename_>_COLUMN_STORE_ -- GEMFIREXD-PROPERTIES executionEngine=Store\n ;

This will give you the distribution of data which has been converted into columnar format.

while this:
select distinct dsid() from <_tablename_> -- GEMFIREXD-PROPERTIES executionEngine=Store\n;

will give you distribution of the data which has not been converted to column format yet. Adding these two member wise will give you the desired result.

**Comment by kneeraj** [comment]
Please use this

select dsid(), count(*) from _tablename_ -- GEMFIREXD-PROPERTIES executionEngine=Store\n; 

as second query.

**Comment by erjunzhang** [comment]
@kneeraj   very   thanks  

use this  query fow now ,  but error 

select numrows, dsid() from SNAPPYSYS_INTERNAL.APP__<tablename>COLUMN_STORE -- GEMFIREXD-PROPERTIES executionEngine=Store\n ;

snappy> select numrows, dsid() from SNAPPYSYS_INTERNAL.APP_NO_WITH COLUMN_STORE -- GEMFIREXD-PROPERTIES executionEngine=Store\n ;
ERROR 42X05: (SQLState=42X05 Severity=20000) (Server=isunode006/192.168.220.140[1527] Thread=pool-3-thread-32) Table/View 'SNAPPYSYS_INTERNAL.APP_NO_WITH' does not exist

**Comment by kneeraj** [comment]
I think the table name is wrong in your query.
The name of column table I created is NEWCOLTAB1 in the default schema APP.
As per that this is the query:
snappy> select numrows, dsid() from SNAPPYSYS_INTERNAL.APP__NEWCOLTAB1_COLUMN_STORE_ -- GEMFIREXD-PROPERTIES executionEngine=Store\n ;
NUMROWS    |_c1                                                                                                                             
--------------------------------------------------------------------------------------------------------------------------------------------
1          |192.168.1.98(2074)<v1>:46668                                                                                                    
1          |192.168.1.98(2074)<v1>:46668                                                                                                    
1          |192.168.1.98(2074)<v1>:46668                                                                                                    
1          |192.168.1.98(2074)<v1>:46668                                                                                                    
1          |192.168.1.98(2074)<v1>:46668                                                                                                    

5 rows selected

Now if your table name is 'ODS_DEV_DEVICE_INFO_D0301'

then your query should be:

select numrows, dsid() from SNAPPYSYS_INTERNAL.APP__ODS_DEV_DEVICE_INFO_D0301_COLUMN_STORE_ -- GEMFIREXD-PROPERTIES executionEngine=Store\n ;

**Comment by erjunzhang** [comment]
ok  
Success now
thanks very much

**Comment by kneeraj** [comment]
@erjunzhang there was a mistake in the query. Forgot to put 'sum' in the query.

The query should be:

select sum(numrows), dsid() from SNAPPYSYS_INTERNAL.APP__ODS_DEV_DEVICE_INFO_D0301_COLUMN_STORE_ -- GEMFIREXD-PROPERTIES executionEngine=Store\n ;

**Comment by jramnara** [comment]
You need a 'group by' to go with the aggregation query ...

select sum(numrows), dsid() from SNAPPYSYS_INTERNAL.APP__ODS_
DEV_DEVICE_INFO_D0301_COLUMN_STORE_ -- GEMFIREXD-PROPERTIES
executionEngine=Store\n  group by dsid();

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://github.com/SnappyDataInc/snappydata>

**Comment by sumwale** [comment]
Support for dsid() using the Spark SQL query engine is being tracked here: https://jira.snappydata.io/browse/SNAP-671 @erjunzhang
