### ISSUE TITLE
Does BUILTIN User Accounts enable in snappydata

### ISSUE THREAD

**Issue by gnuhpc** [SnappyDataInc/snappydata#546]
From the Pivotal GemFire XD doc, user accounts auth can be enabled by specifying the builtin user properrties. I'm wondering whether this can be applied in snappydata.

Thanks !

**Comment by ashetkar** [comment]
This is something we have planned for future SnappyData release and the work is in-progress as of now.

**Comment by gnuhpc** [comment]
OK, looking forwards to that. In fact, I tried many times but failed.  

Keep up your good work!
