### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by ddorian** [SnappyDataInc/snappydata#552]
http://rowstore.docs.snappydata.io/docs/about_gemfirexd/topics/c_what_is_elasticsql.html

RowStore Features and Benefits link is broken: http://rowstore.docs.snappydata.io/docs/about_gemfirexd/topics/snappystore_intro.html

**Comment by ddorian** [comment]
Should point to this I think ? http://rowstore.docs.snappydata.io/docs/about_gemfirexd/topics/gemfirexd_intro.html

**Comment by shyjaprabhu** [comment]
Thank you for bringing this to our attention. The link should point to http://rowstore.docs.snappydata.io/docs/about_gemfirexd/topics/gemfirexd_intro.html

I will make the required changes to the documentation.

**Comment by sumwale** [comment]
Fixed in the docs a while back.
