### ISSUE TITLE
snappyData cannot build normally

### ISSUE THREAD

**Issue by justin201508** [SnappyDataInc/snappydata#595]
I downloaded the SnappyData 8.1 sourcecodes ,but it built failed.
cd /home/hadoop/dev/snappydata-branch-0.8.1
./gradlew product 

this is the failed messages
============================================================
FAILURE: Build failed with an exception.

* Where:
Build file '/home/hadoop/dev/snappydata-branch-0.8.1/build.gradle' line: 612

* What went wrong:
A problem occurred evaluating root project 'snappydata_2.11'.
> Project with path ':snappy-spark' could not be found in root project 'snappydata_2.11'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by rishitesh** [comment]
Did you follow the instructions given in
http://snappydatainc.github.io/snappydata/install/#building-from-source ?

Regards,
Rishitesh Mishra,
SnappyData . (http://www.snappydata.io/)

https://in.linkedin.com/in/rishiteshmishra

**Comment by justin201508** [comment]
Yes,I downloaded the sourcecodes by git clone ,and executed the gradlew command like this:
gradlew idea

But it do not works

**Comment by justin201508** [comment]
I can not find the snappy-spark project in the root source codes directory

**Comment by sumwale** [comment]
Do you see "spark" directory with files/directories inside? You need to use recursive clone as given in the build instructions. Try "./gradlew product" first to check if it works.

Also see instructions for IDEA import in that link below. Will recommend using gradle import of IDEA as mentioned in that link instead of generating using "./gradlew idea".

**Comment by justin201508** [comment]
Yes,I clone the source codes using git clone --recursive command,
If import project using idea ,failed with the following error messages:
================================================
2017-05-16 18:54:47,675 [34403097]   WARN - nal.AbstractExternalSystemTask - No such property: fork for class: org.gradle.api.tasks.scala.ScalaCompileOptions
Possible solutions: force 
com.intellij.openapi.externalSystem.model.LocationAwareExternalSystemException: No such property: fork for class: org.gradle.api.tasks.scala.ScalaCompileOptions
Possible solutions: force

**Comment by sumwale** [comment]
Have you installed the Scala plugin in IDEA (File->Settings->Plugins)?

**Comment by sumwale** [comment]
Also note one important point as in the [link](http://snappydatainc.github.io/snappydata/install/#building-from-source): Un-select the "Create separate module per source set" option in import.

**Comment by justin201508** [comment]
Tks,it works(File->New->Project from Existing Sources and and Import Gradle project,but Import project from external model)

**Comment by sumwale** [comment]
Thanks, closing this. If you think the docs are lacking in some aspect for this, then please mention and will file a doc JIRA.
