### ISSUE TITLE
two conflict versions of class UTF8String

### ISSUE THREAD

**Issue by xfeep** [SnappyDataInc/snappydata#652]
`org/apache/spark/unsafe/types/UTF8String` exists in both `snappydata-client-1.5.4.jar` and `snappy-spark-unsafe_2.11-2.0.2.3.jar`. But they are not the same version and will cause InvalidClassException

```
java.io.InvalidClassException: org.apache.spark.unsafe.types.UTF8String; local class incompatible: stream classdesc serialVersionUID = -2070712160832058135, local class serialVersionUID = -2992553500466442037
```

**Comment by sumwale** [comment]
@xfeep 
This has been fixed in https://jira.snappydata.io/browse/SNAP-1520 that removes the dependency on snappy-spark-unsafe (instead only on upstream spark-unsafe). Fix is in master and will be in 0.9 release which will be available in a few days.
