### ISSUE TITLE
Is AQP now supported?

### ISSUE THREAD

**Issue by xuebinsu** [SnappyDataInc/snappydata#658]
I read your document about AQP(aqp.md), and found that the DataFrame API supporting approximate queries is the 'withError' API. However, It seems that this API has not been implemented yet.(Please correct me if I am wrong.) I was wondering whether any version of SnappyData support AQP and where can I obtain one copy. Thx!

**Comment by svbhokare** [comment]
withError API on DataFrame is implemented in AQP. Please take a look at following section for more details. http://snappydatainc.github.io/snappydata/aqp/#using-the-spark-dataframe-api

AQP is always part of snappy distribution since first release. We have recently released 0.9 version of the product. You can download it from: http://www.snappydata.io/download. Please let us know if you need any further help.

**Comment by xuebinsu** [comment]
Sorry but in which file the withError API is implemented? Thx!

**Comment by sudsmenon** [comment]
AQP has always been a closed source component. Please let us know if you run into any issues.

Thanks

**Comment by xuebinsu** [comment]
Thanks for explanation! Since I'm doing benchmarks on different AQP tools, I was wondering whether there is a way to obtain the execution plans of SnappyData like what we can do with the EXPLAIN command in traditional databases.

**Comment by piercelamb** [comment]
Hi @xuebinsu I just wanted to let you know you may be able to get more immediate help in our Slack chat: http://snappydata-slackin.herokuapp.com/

**Comment by xuebinsu** [comment]
@piercelamb Thx! I'll check that.

**Comment by ymahajan** [comment]
@xuebinsu You can use SnappyData dashboard running at (yourLeadNodeHostname:5050), go to SQL tab, you should be able to see the query/spark plans on the UI itself

**Comment by xuebinsu** [comment]
@ymahajan Thx! I tried some approximate queries presented on your /doc/howtos.md and did see query plans on the dashboard. However, there're still two issues that confusing me:
1. why I could not see any error estimation operators in the plan, e.g., bootstrap or closed form?
2. why no matter how I change the error using the "with error" clause, SnappyData keep giving the same approximate result?

**Comment by svbhokare** [comment]
@xuebinsu

1. Take look at SampleTableQuery node in logical plan, you will get to know the error estimation 
method is closedForm or Bootstrap. I have pasted one such a plan below.

== Analyzed Logical Plan ==
ARRIVALDELAY: double, CARRIER: string, Relative_Error(ARRIVALDELAY): double
SampleTableQuery 0.1, 0.8, org.apache.spark.sql.sources.Masquerader@1470277e, false, false, **Closedform**, ExprId(8885,d68ddfc8-6f91-4627-9ef0-51bd3d7f4f13), 100, DO_NOTHING, AIRLINE_SAMPLE, 5, true, true
+- GlobalLimit 1001
   +- LocalLimit 1001
      +- Project [ARRIVALDELAY#8811, CARRIER#8812]
         +- Sort [CARRIER#8812 ASC], true
            +- Aggregate [UNIQUECARRIER#8851], [ErrorAggregateNumericConverter(closedformerrorestimate(cast(ARRDELAY#8857 as bigint), SNAPPY_SAMPLER_WEIGHTAGE#8873L, 0.8, Avg, 0.1, (2,Avg_Relative,Relative_Error(ARRIVALDELAY),Relative_Error(ARRIVALDELAY),ExprId(8886,d68ddfc8-6f91-4627-9ef0-51bd3d7f4f13),Virtual Error Attrbute#8886 AS Relative_Error(ARRIVALDELAY)#8883), DO_NOTHING)) AS ARRIVALDELAY#8811, UNIQUECARRIER#8851 AS CARRIER#8812]
               +- SubqueryAlias AIRLINE_SAMPLE
                  +- Relation[Year_#8843,Month_#8844,DayOfMonth#8845,DayOfWeek#8846,DepTime#8847,CRSDepTime#8848,ArrTime#8849,CRSArrTime#8850,UniqueCarrier#8851,FlightNum#8852,TailNum#8853,ActualElapsedTime#8854,CRSElapsedTime#8855,AirTime#8856,ArrDelay#8857,DepDelay#8858,Origin#8859,Dest#8860,Distance#8861,TaxiIn#8862,TaxiOut#8863,Cancelled#8864,CancellationCode#8865,Diverted#8866,... 7 more fields] ColumnFormatSamplingRelation[APP.AIRLINE_SAMPLE]

2. "with error"  value only used for specifying error which can be tolerated by user in the approximate answer. It should not change the appromixate answers. You can specify behavior along with error to see what action user wants to take if approximate answers have greater errors than specified. 
Please  also take a look at http://snappydatainc.github.io/snappydata/aqp/#high-level-accuracy-contracts-hac

**Comment by xuebinsu** [comment]
@svbhokare Thanks for your kindly help! Could you please tell me how I can enter the console shown in the pictures in  [high-level-accuracy-contracts-hac](http://snappydatainc.github.io/snappydata/aqp/#high-level-accuracy-contracts-hac)? I can't find it when I run the spark-shell script and visit 127.0.0.1:4040 when I run SnappyData on my laptop.

**Comment by svbhokare** [comment]
@xuebinsu 
1. Those screen shots are taken using zeppelin but you can run those same queries using snappy-shell. If you need details about how to use zeppelin with snappydata & aqp below is the link.
http://snappydatainc.github.io/snappydata/aqp_aws/#snappydata-directives-in-apache-zeppelin

2.User needs to create sample tables in advance only and appropriate sample table is selected automatically for a given query. More details below:
http://snappydatainc.github.io/snappydata/aqp/#qcs-query-column-set-and-sample-selection

**Comment by xuebinsu** [comment]
@svbhokare Thanks for your explanation!
It sounds quite like what BlinkDB does in sample creation. Could you please explain how they differ in sample selection? In my understanding, SnappyData just choose between different sample tables with different fractions based on the same base table. If that's the case, how does it determine which sample fraction is best suited for a query?

**Comment by svbhokare** [comment]
@xuebinsu 
Yes, SnappyData uses the whole sample table and just choose between different sample tables with different fractions& QCSs based on the same base table. We have taken the curated sampling approach which is proposed originally by BlinkDB. This differs from Online Aggregation or Generalized Online Aggregation (G-OLA) which spark SQL supports. 

@sudsmenon 
I don't think, I can disclose SnappyData's sample selection logic here as AQP has been a closed source component, correct?

**Comment by xuebinsu** [comment]
@sudsmenon If that's the case, I guess this issue can be closed.

Thanks all of you guys for such a nice discussion!
