### ISSUE TITLE
Any help for understanding query plans?

### ISSUE THREAD

**Issue by xuebinsu** [SnappyDataInc/snappydata#660]
I executed a query and checked the query plan, which reads

> == Parsed Logical Plan ==
> 'Error 0.20
> +- 'Sort ['FLIGHTRECCOUNT ASC], true
>    +- 'Aggregate ['UNIQUECARRIER, 'DESCRIPTION, 'YEAR_], [unresolvedalias(count(1) AS FLIGHTRECCOUNT#3052L, None), unresolvedalias('DESCRIPTION AS AIRLINENAME#3053, None), unresolvedalias('UNIQUECARRIER AS CARRIERCODE#3054, None), unresolvedalias('YEAR_, None)]
>       +- 'Filter ('AIRLINE.UNIQUECARRIER = 'AIRLINEREF.CODE)
>          +- 'Join Inner
>             :- 'UnresolvedRelation `AIRLINE`
>             +- 'UnresolvedRelation `AIRLINEREF`

However, I get confused when reading it in the following points:
1. how can I find "number of rows affected" attribute for every operator?
2. what do the numbers following column names mean? How can I retrieve them?

**Comment by svbhokare** [comment]
1.  You will get the information about number of output rows under SQL tabs in Spark UI in visual representation for query plan.

2. Numbers following column names are unique exprIds generated by spark while creating query plans.

**Comment by sumwale** [comment]
@xuebinsu Is the above information enough for your needs? If not then need to track as docs issue and/or add more information in SQL plan info.

**Comment by xuebinsu** [comment]
Thanks for your reply! I'm sorry about the delayed response because I was working on another project last month and didn't have time to check it. I checked the diagram and finally found the output rows. 

And here is another thing I want to confirm: before I run an approximate query, I create a sequence of sample tables with different rates, and when I run it, the query plan shows

== Analyzed Logical Plan ==
FLIGHTRECCOUNT: bigint, AIRLINENAME: string, CARRIERCODE: string, YEAR_: int
SampleTableQuery 0.5, 0.95, org.apache.spark.sql.sources.Masquerader@5880bce2, spark_grouping_id#3424: int, false, false, Bootstrap, ExprId(3423,4c4a4b9c-eb08-48e7-ae62-df1efcb8ee4a), 100, REROUTE_TO_BASE, AIRLINE, -1, true, true
+- Sort [FLIGHTRECCOUNT#3349L ASC], true
   +- BootstrapReferencer ExprId(3423,4c4a4b9c-eb08-48e7-ae62-df1efcb8ee4a), spark_grouping_id#3424: int
      +- Aggregate [UNIQUECARRIER#3360, DESCRIPTION#2383, YEAR_#3352], [bootstrapmultiplicityaggregate(MapColumnToWeight(SNAPPY_SAMPLER_WEIGHTAGE#3413L), spark_grouping_id#3424, 100) AS bootstrap_multiplicity_aggregate#3423, ErrorAggregateNumericConverter(bootstrapcount(1, 100, 0.95, 0.5, false, REROUTE_TO_BASE)) AS FLIGHTRECCOUNT#3349L, DESCRIPTION#2383 AS AIRLINENAME#3350, UNIQUECARRIER#3360 AS CARRIERCODE#3351, YEAR_#3352]
         +- Filter (UNIQUECARRIER#3360 = CODE#2382)
            +- Join Inner
               :- Project [YEAR_#3383 AS YEAR_#3352, MONTH_#3384 AS MONTH_#3353, DAYOFMONTH#3385 AS DAYOFMONTH#3354, DAYOFWEEK#3386 AS DAYOFWEEK#3355, DEPTIME#3387 AS DEPTIME#3356, CRSDEPTIME#3388 AS CRSDEPTIME#3357, ARRTIME#3389 AS ARRTIME#3358, CRSARRTIME#3390 AS CRSARRTIME#3359, UNIQUECARRIER#3391 AS UNIQUECARRIER#3360, FLIGHTNUM#3392 AS FLIGHTNUM#3361, TAILNUM#3393 AS TAILNUM#3362, ACTUALELAPSEDTIME#3394 AS ACTUALELAPSEDTIME#3363, CRSELAPSEDTIME#3395 AS CRSELAPSEDTIME#3364, AIRTIME#3396 AS AIRTIME#3365, ARRDELAY#3397 AS ARRDELAY#3366, DEPDELAY#3398 AS DEPDELAY#3367, ORIGIN#3399 AS ORIGIN#3368, DEST#3400 AS DEST#3369, DISTANCE#3401 AS DISTANCE#3370, TAXIIN#3402 AS TAXIIN#3371, TAXIOUT#3403 AS TAXIOUT#3372, CANCELLED#3404 AS CANCELLED#3373, CANCELLATIONCODE#3405 AS CANCELLATIONCODE#3374, DIVERTED#3406 AS DIVERTED#3375, ... 7 more fields]
               :  +- SubqueryAlias AIRLINE
               :     +- Relation[YEAR_#3383,MONTH_#3384,DAYOFMONTH#3385,DAYOFWEEK#3386,DEPTIME#3387,CRSDEPTIME#3388,ARRTIME#3389,CRSARRTIME#3390,UNIQUECARRIER#3391,FLIGHTNUM#3392,TAILNUM#3393,ACTUALELAPSEDTIME#3394,CRSELAPSEDTIME#3395,AIRTIME#3396,ARRDELAY#3397,DEPDELAY#3398,ORIGIN#3399,DEST#3400,DISTANCE#3401,TAXIIN#3402,TAXIOUT#3403,CANCELLED#3404,CANCELLATIONCODE#3405,DIVERTED#3406,... 7 more fields] ColumnFormatSamplingRelation[APP.AIRLINE_SAMPLE20]
               +- SubqueryAlias AIRLINEREF
                  +- Relation[CODE#2382,DESCRIPTION#2383] RowFormatRelation[APP.AIRLINEREF]

Is the table named "APP_AIRLINE_SAMPLE20" the sample used to answer the query?

One more question: how can I obtain the approximation error for a query using shell (without Apache Zeppelin)? For now, I can only see the result.

**Comment by svbhokare** [comment]
Is the table named "APP_AIRLINE_SAMPLE20" the sample used to answer the query?
>> Yes, that's correct. If multiple sample tables are available for a given table, one of the sample table gets selected based on sample selection logic. You can read more about sample selection
here: https://snappydatainc.github.io/snappydata/aqp/#sample-selection

how can I obtain the approximation error for a query using shell (without Apache Zeppelin)? 
>> You can use relative_error() or absolute_error() function as a projection while writing approx queries to obtain error. Details below : https://snappydatainc.github.io/snappydata/aqp/#running-queries

**Comment by xuebinsu** [comment]
Thanks for your reply!
