### ISSUE TITLE
Security Concern - The passed-in password is logged in snappyStore.log

### ISSUE THREAD

**Issue by mp-calebs** [SnappyDataInc/snappydata#668]
Both snappy locator and server will require both -user=dbUser -password=dbPassword to be passed in. I have come up a solution to hide the plain password from anyone who has the access to the machine to see it.  But this plain password is also logged in snappyStore.log file. Since this db user is the admin user to snappyData, we would really like to hide the password completely. 

tx2dcddn020243p:~/server/logs$ grep sun.java.command snappyStore.log 
    sun.java.command = io.snappydata.tools.ServerLauncher server -critical-heap-percentage=90 -eviction-heap-percentage=81 locators=tx2dcddn020442p:10334 **user=db_snappy_admin** **password=AdminPassword** security-log-file=/mnt/disk3/snappy/data/server/security.log log-file=snappyserver.log -client-bind-address=tx2dcddn020243p

Is there a way that we can hide it?

**Comment by ymahajan** [comment]
@mp-calebs Have you tried SnappyData encrypt-password utility? refer this link for how to use it - http://rowstore.docs.snappydata.io/docs/reference/store_commands/store-encrypt-password.html

**Comment by sumwale** [comment]
@mp-calebs If you are using BUILTIN scheme then the encrypt-password can be used. Otherwise you can just skip the =... option and the password will be prompted at command-line:

... -user=dbUser -password

**Comment by mp-calebs** [comment]
@ymahajan I use our own UserAuthenticator, where a plain password is expected. If I pass in a encrypted password generated by SnappyData tool on the command line, will our UserAuthenticator get the plain password?  

@sumwale This issue here is not about having passed-in password from the command line. I've written a tool to get the password from an encrypted password file. The main problem here is the password is showing up on the snappyStore.log file. Is there a way that I can do so that it won't log the password on the file?

**Comment by sumwale** [comment]
@mp-calebs that's what I said you can do for now. Full command-line is logged currently so you can skip password in startup:

... -auth-provider=... -user=... -password

Then the product will prompt for password on command-line and you will not have it in the logs. We will look at masking it out in the log meanwhile.

**Comment by mp-calebs** [comment]
@sumwale The service will be started/stopped via /etc/init upstart service. And we manage these services via Rundeck. So there is no way for us to enter the password. Do thank you for planning to masking it out.

**Comment by sumwale** [comment]
@mp-calebs A more general task about password logging/handling is being tracked here: https://jira.snappydata.io/browse/SNAP-1657

**Comment by sumwale** [comment]
@mp-calebs Closing this since many fixes to this are already in 1.0 RC release while remaining are being tracked in [SNAP-1657](https://jira.snappydata.io/browse/SNAP-1657). Going forward our thinking as a general fix to all clear text password logging, storage, transfer is using PKCS encryption with a user provided key pair.
