### ISSUE TITLE
problem in installing snappy cluster 

### ISSUE THREAD

**Issue by anubhavj880** [SnappyDataInc/snappydata#681]
I have three VM and i downloaded the snappy zip in all three vm . 
VM1-ip=192.168.1.171(master)
VM2-ip=192.168.1.172(worker)
VM3-ip=192.168.1.173(worker)
I just configure the slaves and spark-env file in conf folder for each vm like configuration which are required for normal spark standalone cluster.
i set export SPARK_MASTER_HOST=192.168.1.171 ,this in all three vm spark-env file and in both slave vm 
export SPARK_WORKER_CORES=2
export SPARK_WORKER_MEMORY=1g
export SPARK_WORKER_INSTANCES=1
after this when i start spark cluster it start as normal but along with slaves and spark-env file there are three more config file i.e locator , leads and server i do not understand how to configure this 

Suppose if i want locator on VM1 the should i update locator file in all three and same with leads file.
And Is there any webUI for snappy like spark and if it is then on what is the default port.

**Comment by ymahajan** [comment]
Do you intend to use SnappyData in smart connector mode (with existing spark cluster?) Or you want to use spark embedded in SnappyData. For later, you don't have to setup the spark cluster. 

Yes, you need to configure conf/locators, conf/leads, conf/servers files, you can follow the instructions here  - https://snappydatainc.github.io/snappydata/configuration/

The web UI port is 5050 and hostname will be your lead node host.

**Comment by anubhavj880** [comment]
I want to use spark embedded in SnappyData

**Comment by sumwale** [comment]
Assuming you want to run Spark code in the embedded SnappyData cluster, you can use either jobs (https://snappydatainc.github.io/snappydata/howto/#how-to-run-spark-code-inside-the-cluster) or Zeppelin (https://snappydatainc.github.io/snappydata/howto/#how-to-use-apache-zeppelin-with-snappydata).

Just look through that HowTos section. It gives step-by-step on all options you have with a SnappyData cluster.

**Comment by sumwale** [comment]
You can also run spark-shell in local[*] mode for local testing.

**Comment by anubhavj880** [comment]
@sumwale can you please answer the above question because i am facing problem in installing cluster of snappy

**Comment by sumwale** [comment]
Closing the issue since cluster configuration is documented well in howtos and otherwise. If there still are issue please use slack (or stackoverflow with snappydata tag).
