### ISSUE TITLE
PUT INTO throws java.sql.BatchUpdateException for duplicate values

### ISSUE THREAD

**Issue by jestan** [SnappyDataInc/snappydata#701]
After updating snappydata-store-client to 1.5.5 with snappydata 0.9, PUT INTO throws BatchUpdateException  for duplicate values, but it should not throw errors according to https://snappydatainc.github.io/snappydata/reference/sql_reference/put-into/

```
java.sql.BatchUpdateException: (Server=snappy-db.service.consul/127.0.0.1[1555] Thread=pool-3-thread-10) The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'primary key constraint' defined on 'APP.MESSAGE_HISTORY'.
	at io.snappydata.thrift.SnappyDataService$executePreparedBatch_result$executePreparedBatch_resultStandardScheme.read(SnappyDataService.java:15625) ~[snappydata-store-shared-1.5.5.jar:?]
	at io.snappydata.thrift.SnappyDataService$executePreparedBatch_result$executePreparedBatch_resultStandardScheme.read(SnappyDataService.java:15602) ~[snappydata-store-shared-1.5.5.jar:?]
	at io.snappydata.thrift.SnappyDataService$executePreparedBatch_result.read(SnappyDataService.java:15541) ~[snappydata-store-shared-1.5.5.jar:?]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~[libthrift-0.9.3.jar:0.9.3]
	at io.snappydata.thrift.SnappyDataService$Client.recv_executePreparedBatch(SnappyDataService.java:461) ~[snappydata-store-shared-1.5.5.jar:?]
	at io.snappydata.thrift.SnappyDataService$Client.executePreparedBatch(SnappyDataService.java:445) ~[snappydata-store-shared-1.5.5.jar:?]
	at io.snappydata.thrift.internal.ClientService.executePreparedBatch(ClientService.java:1304) ~[snappydata-store-client-1.5.5.jar:?]
	at io.snappydata.thrift.internal.ClientPreparedStatement.executeBatch(ClientPreparedStatement.java:278) ~[snappydata-store-client-1.5.5.jar:?]
```

Also we have noticed, new standalone JDBC driver (snappydata-store-client-1.5.5 jar) seems missing some dependencies  (throws thrift/spark class not found errors), to fix it, had to use snappydata-core_2.11-0.9

PUT INTO worked properly in snappydata-store-client-1.5.3 and snappydata-0.7

**Comment by jestan** [comment]
After trying to find duplicate entry in source file (which has 1 million records), it seems the error is not about duplicate entry at all,  it was due to very high insertion rate

**Comment by sumwale** [comment]
@jestan 

The self-contained store client is the "snappydata-client-1.5.5.jar" available separately on the releases page and is not bundled in the main product tar/zip (or when building from source then "./gradlew distProduct" target will create it in build-artifacts/scala-2.11/distributions). The one in the product distribution is the one without any dependencies as appropriate for maven/gradle/sbt dependencies and same as the one published on maven central.

About the putInto issue, the problem seems to be that it was retried by Spark due to some reason and in the retry there was some issue causing the error. Can you provide the lead and server logs?

**Comment by jestan** [comment]
@sumwale 
Please ignore my second comment, which says "data has no duplicates". Sorry I had an issue with  my duplicate counting script (in-fact the data file has lots of duplicates and we are injecting it to snappydata via a log injector application @  50000 records per second).

I was able to narrow down the cause. it seems it has nothing to do with duplicates and it was related PARTITION_BY clause.

- Test Scenario 1 (1 million records (with duplicates) to ROW table without any OPTIONS)
   
    SnappyData 0.7 - OK
    SnappyData 0.9 - OK

- Test Scenario 2 ( 1 million records (with duplicates) to ROW table with OPTIONS PERSISTENCE 'ASYNC', OVERFLOW 'true', EVICTION_BY 'LRUHEAPPERCENT')

    SnappyData 0.7 - OK
    SnappyData 0.9 - OK

- Test Scenario 3 (1 million records (with duplicates) to ROW table with  OPTIONS (PARTITION_BY 'device_id', PERSISTENCE 'ASYNC', OVERFLOW 'true', EVICTION_BY 'LRUHEAPPERCENT'))

   SnappyData 0.7 -  Failed
    SnappyData 0.9 - Failed 

Can PARTITION_BY requires more than 2 dataserver?
We have 1 - locator , 1 - leader, 1 - dataserver in the test setup and no error logs in any server
Since It is not mentioned in [the guide](http://snappydatainc.github.io/snappydata/reference/sql_reference/create-table/#example-row-table-partitioned-with-10-buckets-and-overflow-enabled), I have tried the test again with 3 - data nodes


- Test Scenario 4 (1 million records (with duplicates) to ROW table with  OPTIONS (PARTITION_BY 'device_id', PERSISTENCE 'ASYNC', OVERFLOW 'true', EVICTION_BY 'LRUHEAPPERCENT'))

SnappyData 0.8 - Failed
 SnappyData 0.9 - Failed [logs are available here
](https://www.dropbox.com/sh/p04rryswpqlv508/AAD558JEYsNXD6Z4wWtSEcysa?dl=0)

- Test Scenario 5 (1 million records (no duplicates) to ROW table with  OPTIONS (PARTITION_BY 'device_id', PERSISTENCE 'ASYNC', OVERFLOW 'true', EVICTION_BY 'LRUHEAPPERCENT'))

SnappyData 0.8 - OK
 SnappyData 0.9 - OK

So can there be an issue with PARTITION_BY and duplicate records?

**Comment by jestan** [comment]
@sumwale 

We have slightly changed the schema and got it working with 'partition by' on primary key.
It is reproducible with 'partition by' on some other column

**Comment by jestan** [comment]
@sumwale 
I tried to reproduce this issue with smaller data set, but partition by works for smaller data set with any column. I assume the root cause of 'BatchUpdateException' might be some thing else. So i am closing this for now.
