### ISSUE TITLE
Smart connector mode - Initializing snappysession with authentication enabled

### ISSUE THREAD

**Issue by ckatili** [SnappyDataInc/snappydata#715]
Hey,

I am trying to load data from parquet file (in our other cluster) to snappydata cluster using smart connector to a snappydata that has authentication enabled.

Your examples:
- https://github.com/SnappyDataInc/snappydata/blob/master/examples/src/main/scala/org/apache/spark/examples/snappydata/SmartConnectorExample.scala

- https://github.com/SnappyDataInc/snappydata/blob/master/docs/howto.md#howto-load, 

show how to instantiate snappysession without passing credential.

How can one pass the credential so we can instantiate snappysession successfully with proper credential?

Note: I know I can use jdbc and access snappydata as datasource. The above question is strictly when using snappysession.

**Comment by ashetkar** [comment]
@ckatili Security in snappydata will be available in upcoming 1.0 release.

**Comment by sumwale** [comment]
@ckatili As mentioned above, security as a general feature for SnappyData is being tracked for 1.0 GA release (you can see the tickets under the [Security](https://jira.snappydata.io/issues/?jql=project%20%3D%20SNAP%20AND%20status%20in%20(%22In%20Progress%22%2C%20%22To%20Do%22%2C%20%22In%20Review%22)%20AND%20fixVersion%20%3D%201.0%20AND%20component%20%3D%20Security) component on jira.snappydata.io).

**Comment by sumwale** [comment]
@ckatili Security with LDAP for authentication and standard SQL (GRANT/REVOKE) for authorization is available now starting with enterprise 1.0 RC release (http://www.snappydata.io/download).
