### ISSUE TITLE
SnappyData0.9 paging query failed

### ISSUE THREAD

**Issue by diwenjing** [SnappyDataInc/snappydata#725]
I failed with the snappydata0.9 query, and the snappydata0.8 query succeeded.

```
select * from DATASET_F8A2F8A218DB4D7F85C01A89471C0FF0 offset 5 rows fetch next 5 rows only；
错误 38000：(SQLState=38000 Severity=20000) (Server=cloudera1/192.168.15.122[1527] Thread=pool-3-thread-389) 求值表达式时抛出异常“Invalid input '5', expected WHERE, WITH, INTERSECT, join, EXCEPT, CONFIDENCE, HAVING, commaSep, queryOrganization, groupBy, BEHAVIOR or UNION (line 1, column 63):
select * from DATASET_F8A2F8A218DB4D7F85C01A89471C0FF0 offset 5 rows fetch next 5 rows only
```

**Comment by sumwale** [comment]
@diwenjing Is the table `DATASET_F8A2F8A218DB4D7F85C01A89471C0FF0` a column table? The "offset" and "fetch next" clauses are supported by rowstore but not by Spark engine. Support for LIMIT is available in Spark but support for OFFSET is not present in Spark. If the table is a row table, you can force running the query on the rowstore side either by setting "route-query=false" in connection property or adding an executionEngine hint to query:

```sql
snappy> select * from DATASET_F8A2F8A218DB4D7F85C01A89471C0FF0 --GEMFIREXD-PROPERTIES executionEngine=Store
> offset 5 rows fetch next 5 rows only；
```

**Comment by sumwale** [comment]
@diwenjing Did you try with above suggestion? Support for OFFSET clause (along-with existing LIMIT clause) in SnappyData's Spark engine is being tracked in [SNAP-1515](https://jira.snappydata.io/browse/SNAP-1515) so closing this.
