### ISSUE TITLE
SnappyData create external table failed

### ISSUE THREAD

**Issue by diwenjing** [SnappyDataInc/snappydata#726]
Failed to create external table in cluster mode:
```
snappy> create external table test_iris using csv options(path '/opt/snappyData-0.9/iris.csv');
错误 38000：(SQLState=38000 Severity=20000) (Server=cloudera1/192.168.15.122[1527] Thread=pool-3-thread-388) 求值表达式时抛出异常“com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: cloudera1(11577)<v1>:29455, caused by java.io.IOException: Failed to create local dir in /tmp/blockmgr-9d1f9c3b-1d22-4070-9b68-9600553f4033/0c.”。
```
create success in standalone mode：
```
snappy> create external table test_iris using csv options(path '/opt/snappyData-0.9/iris.csv');
snappy> show tables in app;
TABLE_SCHEM         |TABLE_NAME                    |TABLE_TYPE    |REMARKS             
---------------------------------------------------------------------------------------
APP                 |TEST_IRIS                     |EXTERNAL TABLE|
```

**Comment by sumwale** [comment]
@diwenjing Looks to be some problem in creating directories in /tmp. This is pretty standard thing which is tested all the time and have not seen such an issue. As the error states, can you check the permissions of /tmp/blockmgr-9d1f9c3b-1d22-4070-9b68-9600553f4033? Maybe stop the cluster, then remove all /tmp/blockmgr* directories, then restart.

**Comment by diwenjing** [comment]
My directory has read and write privileges, or I can't create a change file automatically. I created the file directory manually and created a look that would be successful

**Comment by sumwale** [comment]
@diwenjing Closing this as this is something to do with directory permissions. If the problem persists with latest releases due to some permissions problem, then try setting "spark.local.dir" property to point to a different location that has your ownership (see https://spark.apache.org/docs/2.1.1/configuration.html). Please re-open if issue is still not resolved with these.
