### ISSUE TITLE
Error while loading data into SnappyData

### ISSUE THREAD

**Issue by xuebinsu** [SnappyDataInc/snappydata#755]
When I load a ~600MB Parquet data into SnappyData, it crashes with error message

> 11:20:44.730 CST Executor task launch worker-6<tid=0xad> INFO SNAPPY: info: Management is disabled, MBeans won't be available.
17/08/02 11:20:44.730 CST Executor task launch worker-6<tid=0xad> INFO SNAPPY: TraceFabricServiceBoot: GemFireStore service stopped successfully, notifying status ... 
17/08/02 11:20:44.731 CST Thread-1<tid=0x> INFO BlockManager: BlockManager stopped
17/08/02 11:20:44.733 CST Executor task launch worker-6<tid=0xad> INFO SNAPPY: java.sql.SQLException(XJ040): Failed to start database 'snappydata', see the cause for details.

The data file is randomly generated using the following Scala code
```scala
import breeze.numerics.pow
import org.apache.spark.sql._
import org.apache.spark.sql.types._
import org.apache.spark.mllib.random.RandomRDDs._
import org.apache.spark.rdd.RDD

val normal = normalRDD(sc, pow(10, 8))
val rows: RDD[Row] = normal.map(x => Row(x, 1))
val schema = new StructType().add(StructField("Data", DoubleType, nullable = false)).add(StructField("Label", IntegerType, nullable = false))
val data = spark.createDataFrame(rows, schema)
data.write.parquet("simData8")
```

The Scala code that caused the error is
```scala
import org.apache.spark.sql._

val snSession = new SnappySession(sc)
snSession.sql("CREATE EXTERNAL TABLE STAGING_SIM8 " +
    "USING parquet OPTIONS(path " + s"'simData8')")
snSession.sql("CREATE TABLE SIM8 USING column AS (SELECT Data, Label FROM STAGING_SIM8)")
```

The error can be reproduced by running the code line-by-line in spark-shell.

**Comment by jramnara** [comment]
You probably ran out of memory. What do the logs indicate ?

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://github.com/SnappyDataInc/snappydata>

**Comment by xuebinsu** [comment]
@jramnara Thanks for your reply! It may be true because when I change the scale factor to 7 (i.e., the data size is reduced to ~60 MB), no error is produced. However, I don't think that SnappyData can only handle such a small amount of data on my 32 GB memory machine. What should I look for in the log?

**Comment by sumwale** [comment]
@xuebinsu What is the JVM heap size you are using? Spark's columnar parquet reader produces lots of intermediate large buffers. In our experience the heap-size needs to be at least 8GB for comfortable usage with parquet import. Try starting the spark-shell with "--driver-memory 8G"

Also in local[*] mode like this, the ResourceManager does not get initialized so it will not be able to protect against OOMEs. You need to explicitly set some parameters to get that to work if you want to load data much larger than available heap-size (snappydata.store.critical-heap-percentage=95, spark.memory.manager=org.apache.spark.memory.SnappyUnifiedMemoryManager). In cluster mode with snappy-start-all script these parameters are setup by default.

**Comment by xuebinsu** [comment]
@sumwale Thanks! The error is fixed by setting the driver-memory parameter. Could you please provide guide to set extra parameters? I cannot set the two parameters you mentioned in spark-shell.

**Comment by sumwale** [comment]
@xuebinsu Pass those using --conf i.e. spark-shell --conf snappydata.store.critical-heap-percentage=95 --conf spark.memory.manager=org.apache.spark.memory.SnappyUnifiedMemoryManager ... Check the help output of spark-shell --help for how to set different options.

**Comment by xuebinsu** [comment]
Thanks! I think this issue can be closed. By the way, since I'm doing benchmarks, any suggestion that can optimize the performance of SnappyData is welcome.

**Comment by sumwale** [comment]
@xuebinsu In general we have recommendations on using collocation, NOT EXISTS instead of NOT IN, using off-heap (only in enterprise version since 1.0) if there are GC problems especially with overflow where heap is smaller than data and some others. There are some recommended JVM flags most of which are applied in cluster mode. You can check the two sections here: https://snappydatainc.github.io/snappydata/best_practices/. But perhaps it is better for you to first test it out and then come back with any performance issues you see so we can give specific recommendations.

**Comment by xuebinsu** [comment]
Thanks to @sumwale. I'll check that.
