### ISSUE TITLE
problems with increasing limit on number of columns

### ISSUE THREAD

**Issue by LarrySchumacher** [SnappyDataInc/snappydata#769]
We have a use case that requires more than 1012 columns. We tried modifying the below RowStore limits/constants to 2012 and ran into java.lang.StackOverflowError when we queried the table. We bumped up the java stack size and was able to get the query to run with 1800 columns. 

source/store/gemfirexd/shared/src/main/java/com/pivotal/gemfirexd/internal/shared/common/reference/Limits.java:  public static final int DB2_MAX_COLUMNS_IN_TABLE = 1012;
source/store/gemfirexd/shared/src/main/java/com/pivotal/gemfirexd/internal/shared/common/reference/Limits.java:  public static final int DB2_MAX_ELEMENTS_IN_SELECT_LIST = 1012;
source/store/gemfirexd/shared/src/main/java/com/pivotal/gemfirexd/internal/shared/common/reference/Limits.java:  public static final int DB2_MAX_ELEMENTS_IN_ORDER_BY = 1012;

We also tried creating a ColumnStore table with approximately 4800 columns (I believe the default ColumnStore limit is 5000?) and had  java.lang.StackOverflowError issues as well. We kept bumping the stack size but we could not query the table. Shortly after we had cluster stability issues and had to reinstall and restore database.

Is the 1012 a hard limit we should not exceed for rowstore tables?
Is the columnstore limit 5000? if so what else do we need to configure to support 5000 columns?

**Comment by jramnara** [comment]
Are you able to load data into either the row or column table ?
Was your query a 'select *' ? Try projecting a few columns to see if that works. 
We generate code and the quantity of code is proportional to the width and there are still issues with very wide tables.

**Comment by LarrySchumacher** [comment]
With the rowstore test we were eventually able to create,load, and query the table after adjusting stack size.

For the columnstore we could not create the table with 5000 columns. We kept bumping up the stack size on the dataservers until finally the dataserver would not start because of "0 storage size" error. The final stacksize which triggered this error was 96MB. We then restored stack size to 16MB but the dataserver still would not come up. We had to clear out all table data to get it to come back up.

**Comment by sumwale** [comment]
@LarrySchumacher We are not supporting anything more than thousand columns for either of row tables or column tables. Supporting some huge limit like 5000 columns requires some basic changes to code generation (both Spark layer and to SnappyData additions) which is too much work. Changing stack size will almost certainly cause more trouble, and other basic limits like JVM 8K limit on bytecode etc will be hit much before. You will need to normalize the tables a bit and we are not going to support anything more than a thousand columns for any of the table types for coming releases. Thanks.
