### ISSUE TITLE
"ASSERT FAILED Number of parameters expected" When SnappyData Client try to connect Server using JDBC

### ISSUE THREAD

**Issue by theseusyang** [SnappyDataInc/snappydata#790]
I have 2 machines ，a windows as a SnappyData Client，and another linux  as a Snappydata Server ，it is standalone not Distributed Cluster，When SnappyData Client try to connect Server using JDBC，

there is a fusing error，Caused by: AssertFailure: ASSERT FAILED Number of parameters expected for message id 40XD0 (0) does not match number of arguments received (2)
    at com.pivotal.gemfirexd.internal.shared.common.sanity.SanityManager.ASSERT(SanityManager.java:260)

All the config settings is default in Server Node. the Client JDBC Connection also is simple setting ， jdbc:snappydata://192.168.11.23:1527

**Comment by jramnara** [comment]
@theseusyang Can you copy/paste the exception stack? This is likely reported in the server log (work/...serverx/snappyserver.log) . I am wondering if there is a version mismatch between your JDBC driver and the cluster.

**Comment by theseusyang** [comment]
on  Linux Server, I put a SnappyServer as backend DataServer.
in the servers.xml, the configuration is   "snappytest   -dir=/tmp/data/server -locators=snappytest:9988"
in the locators.xml, the configuration is "snappytest -peer-discovery-address=snappytest  -dir=/tmp/data/locator"
in the leads.xml, the configuration is "snappytest   -dir=/tmp/data/server -locators=snappytest:9988
"
and in /etc/hosts file, the configuration is 
"127.0.0.1       localhost       localhost.localdomain
192.168.99.102 snappytest"

when I run ./snappy-start-all.sh , the log information is following:
snappytest: Starting SnappyData Locator using peer discovery on: snappytest[10334], other locators: snappytest:10334,localhost:10334
snappytest: Starting Thrift server for SnappyData at address snappytest/192.168.99.102[1527]
snappytest: Logs generated in /tmp/data/locator/snappylocator.log
snappytest: SnappyData Locator pid: 2725 status: waiting
snappytest: Waiting for table GFXD_PdxTypes (DiskId: ee63683a-b49a-4c11-bd74-9f8819b9f0d5, Location: /tmp/data/locator/./datadictionary) on: 
snappytest:  [DiskId: 308de724-f211-4f0a-8ac0-07ea0fe1b0d4, Location: /usr/local/snappydata-0.9-bin/work/localhost-server-2/./datadictionary]
Starting SnappyData Locator using peer discovery on: localhost[10334], other locators: snappytest:10334,localhost:10334
Starting Thrift server for SnappyData at address localhost/127.0.0.1[1527]
Logs generated in /usr/local/snappydata-0.9-bin/work/localhost-locator-2/snappylocator.log
SnappyData Locator pid: 2892 status: stopped
Error starting server process: 
BindException: 地址已在使用 (Bind failed) - See log file for details.

**Comment by theseusyang** [comment]
another error happened that is associated with this error.
<code>
snappytest: Starting SnappyData Locator using peer discovery on: snappytest[10334], other locators: snappytest:10334,localhost:10334
snappytest: Starting Thrift server for SnappyData at address snappytest/192.168.99.102[1527]
snappytest: Logs generated in /tmp/data/locator/snappylocator.log
snappytest: SnappyData Locator pid: 2663 status: stopped
snappytest: Error starting server process: 
snappytest: IllegalStateException: The following required files could not be found: *.crf files with these ids: [7], *.drf files with these ids: [7]. - See log file for details.
Starting SnappyData Locator using peer discovery on: localhost[10334], other locators: snappytest:10334,localhost:10334
Starting Thrift server for SnappyData at address localhost/127.0.0.1[1527]
Logs generated in /usr/local/snappydata-0.9-bin/work/localhost-locator-2/snappylocator.log
SnappyData Locator pid: 2830 status: stopped
Error starting server process: 
RuntimeException: This process is attempting to join with a loopback address (null) using a locator that does not have a local address (snappytest/192.168.99.102).  On Unix this usually means that /etc/hosts is misconfigured. - See log file for details.
root@snappytest's password: 
snappytest: Starting SnappyData Server using locators for peer discovery: snappytest:9988
snappytest: Starting Thrift server for SnappyData at address snappytest/192.168.99.102[1527]
snappytest: Logs generated in /tmp/data/server/snappyserver.log
snappytest: SnappyData Server pid: 3188 status: stopped
snappytest: Error starting server process: 
snappytest: GemFireConfigException: Unable to contact a Locator service (timeout=5000ms). Operation either timed out or Locator does not exist. Configured list of locators is "[snappytest(null)<v0>:9988]". - See log file for details.
Starting SnappyData Server using locators for peer discovery: snappytest:10334,localhost:10334
Starting Thrift server for SnappyData at address localhost/127.0.0.1[1527]
Logs generated in /usr/local/snappydata-0.9-bin/work/localhost-server-2/snappyserver.log
SnappyData Server pid: 3323 status: stopped
Error starting server process: 
GemFireConfigException: Unable to contact a Locator service (timeout=1000ms). Operation either timed out or Locator does not exist. Configured list of locators is "[snappytest(null)<v0>:10334, localhost(null)<v0>:10334]". - See log file for details.
root@snappytest's password: 
snappytest: Starting SnappyData Leader using locators for peer discovery: snappytest:9988
snappytest: Logs generated in /tmp/data/server/snappyleader.log
snappytest: SnappyData Leader pid: 3685 status: stopped
snappytest: Error starting server process: 
snappytest: GemFireConfigException: Unable to contact a Locator service (timeout=5000ms). Operation either timed out or Locator does not exist. Configured list of locators is "[snappytest(null)<v0>:9988]". - See log file for details.
Starting SnappyData Leader using locators for peer discovery: snappytest:10334,localhost:10334
Logs generated in /usr/local/snappydata-0.9-bin/work/localhost-lead-2/snappyleader.log
SnappyData Leader pid: 3853 status: stopped
Error starting server process: 
GemFireConfigException: Unable to contact a Locator service (timeout=1000ms). Operation either timed out or Locator does not exist. Configured list of locators is "[snappytest(null)<v0>:10334, localhost(null)<v0>:10334]". - See log file for details.

</code>

**Comment by theseusyang** [comment]
whether I shouldn't  use peer-discovery?

**Comment by theseusyang** [comment]
I correct it.  in configuration files, I don't remove default items, cause duplicated item happens.

**Comment by subhendusa** [comment]
@theseusyang How did you fix it?
