### ISSUE TITLE
Update support join

### ISSUE THREAD

**Issue by luoruixing** [SnappyDataInc/snappydata#902]
now ,update support join ?

 i use update with inner join is wrong

**Comment by sumwale** [comment]
@luoruixing You can use update with sub-queries within (which get translated to join plans). For example:

```sql
update t1 set c1=... where c2 in (select c2 from t2 where ...)

OR (might be more efficient)

update t1 set c1=... where exists (select (1) from t2 where t1.c2 = t2.c2)
```

The plans in the GUI (SQL tab, select update statement) should have a join followed by update below. What is the update statement you are trying?

**Comment by mshtelma** [comment]
@sumwale this is not going to help, if I have to use the field value from joined table in update expression itself

**Comment by luoruixing** [comment]
@sumwale 
I have a sql like this:
  UPDATE TABLEA a
     INNER JOIN TABLEB b  ON a.Id=b.Id
   SET a.Price1=a.Price1-b.Price2
  WHERE a.Type='VALUE';

the step of set is support?

**Comment by rishitesh** [comment]
With the latest version, 1.0.1 updates with joins are supported. An example syntax is

`update  col_table set a.col3 = b.col3 from col_table a join row_table b on a.col2 = b.col2`
