### ISSUE TITLE
 Why the configuration -dir for snappydata server can not be a comma-separated list of multiple directories on different disks?

### ISSUE THREAD

**Issue by alexBaiJW** [SnappyDataInc/snappydata#981]
In the Snappydata document for snappydata server configuration, I find the following description:

> -dir : The working directory of the server that contains the SnappyData Server status file and the default location for the log file, persistent files, data dictionary, and so forth (defaults to the current directory).

And there holds a lot of BACKUPGFXD-DEFAULT-DISKSTORE_x files, which is large enough,  so why the configuration -dir for snappydata server can not be a comma-separated list of multiple directories on different disks?

**Comment by sumwale** [comment]
@alexBaiJW The default diskstore does not have an option for multiple directories. Create a separate diskstore and specify multiple directories (so then the files you mention will be spread over those directories): https://snappydatainc.github.io/snappydata/reference/sql_reference/create-diskstore/
Then use the diskstore option in the tables you want to go there: https://snappydatainc.github.io/snappydata/reference/sql_reference/create-table/

This is recommended in any case to use separate data area from server working directory.

@shyjaprabhu Can we add this to the description of "-dir"?

**Comment by alexBaiJW** [comment]
Year, I had already noticed it. In my opinion, It would be very nice if that allows users to set multiple directories in the configuration file.
