### ISSUE TITLE
How to get the HA benefits when I use the JDBC connection?

### ISSUE THREAD

**Issue by alexBaiJW** [SnappyDataInc/snappydata#986]
The document said: 

> With multiple locators, clients notice nothing and the fail over recovery is completely transparent.

SnappyData documentation  seem to indicate that a JDBC thin client connection goes from a client to a Locator and then it is routed to a direct connection to a Server. So the connected clients will continue to function even when the locator goes away.

And I want to know  how to get the ha benefit when I use the JDBC connection? And Is it possible? 
`Connection connection = DriverManager.getConnection ("jdbc:snappydata://xx:1527/");`

**Comment by kneeraj** [comment]
@alexBaiJW if you have multiple servers and the connection url contains the locator host port then the system will automatically give you HA benefit and the user doesn't have to configure anything from outside.
Similarly for locators and leads we should ideally keep at least 2 each of them and the system will automatically use the other if one is down.

**Comment by alexBaiJW** [comment]
@kneeraj  Does it mean I need maintain a connection instance inside the long-running application, instead of to create a new one when I want to execute a sql command?

**Comment by kneeraj** [comment]
@alexBaiJW we don't have to maintain extra connections.

I believe you must be creating connections ( JDBC thin client ) in you app. And for this you must be using (xx:1527) where xx is the hostname of the locator, in your url. If this is the case then the connection underneath has an actual connection to one of the data servers and one connection to locator. If the data server to which it is connected to goes down then the client connection automatically connects to one of the other data servers in the system.

**Comment by alexBaiJW** [comment]
@kneeraj  I mean I am afraid of the failure of the locator that I am using, If it goes down, I have to try to create a new connection using the other locator.

**Comment by kneeraj** [comment]
You can have an extra locator for that, ( see my first comment ), in the system. Clients get connected to the other one in case the one to which it is connected to goes down.

**Comment by alexBaiJW** [comment]
@kneeraj, year, in my opinion, creating connections is an expensive operation, and I will try it out.Thanks very much.

**Comment by kneeraj** [comment]
@alexBaiJW I did not understand your last comment. Which extra connection are you talking about? These are created just once and when a failure happens.
We need to be more elaborate in the HA section in our docs I feel. @shyjaprabhu let us track this.

**Comment by alexBaiJW** [comment]
@kneeraj  I am sorry, maybe I do not describe it clearly. Now I will  redescribe it as follows.

First,  I have two locators(call locator1 and locator2) in my cluster, and My application is long-running backend service. 

Second, in my opinion, creating a connection is  an expensive operation, so I maintain a connection instance inside my application. And as I can not specify multiple locators in the connection url,  so I specify the locator1 in the connection url.

 I have two questions as follows, and I want to make sure if I have understand it.
1.  if the loactor1 goes down, as we said, the connection can still work well, so does my application.
2. Since the locators' status is uncertain , so when I create the connection, I will have to traverse the locators until I can get a normal connection.

**Comment by kneeraj** [comment]
@alexBaiJW Thanks for explaining. Here are the answers:

>> And as I can not specify multiple locators in the connection url, so I specify the locator1 in the connection url.

Even if only one locator is specified in the url, the locator which it gets connected to knows about other locators in the system. So as a user we do not have to worry about specifying multiple locators at all. If that locator fails then the connection object will internally create a connection to the next locator. The app will never come to know about it.

>> if the loactor1 goes down, as we said, the connection can still work well, so does my application.

Yes.

>> Since the locators' status is uncertain , so when I create the connection, I will have to traverse the locators until I can get a normal connection.

No. as explained earlier as long as one of the locator is up and running and at least one of the server is up and running then the connection will transparently get connected to a valid server and a valid locator and the app does not have to worry about it. Please note again - This all happens transparently even if specification of multiple locator is not done in the url.

Hope this helps.

**Comment by alexBaiJW** [comment]
@kneeraj, Thank you for your patience and detailed answer. I said:

> when I create the connection, I will have to traverse the locators until I can get a normal connection.

Which I mean when I start the app.

Thanks again, and I will close the issue.

**Comment by kneeraj** [comment]
When you acquire a connection, using the host:port of one locator then other locators which are there in the system will be automatically discovered by your client. In the event of failure of one locator the client is intelligent enough to connect to the second locator on its own which it had discovered during the first connection.
You can also use the property 'secondary-locators' while obtaining a connection to explicitly tell your client about other locators which are there in the system or you may start later. Please look at:
https://snappydatainc.github.io/snappydata/reference/configuration_parameters/secondary-locators/
