### ISSUE TITLE
Data Insert Error

### ISSUE THREAD

**Issue by swjung94** [SnappyDataInc/snappydata#988]
I have experienced this case several times in previous versions of SnappyData and have also experienced the new 1.0.1 version.
When I inputted a lot of data into SnappyData, the memory usage was almost full and the last data input operation failed.
I deleted some tables and re-inputted the data, but the operation failed and an error occurred.
In this case, I restarted SnappyData using snappy-stop -all.sh and snappy-start -all.sh.
Then, if I do the same thing that I had previously failed to input, the operation succeeds.

Is there a way to fix this without restarting SnappyData?
Below is a part of the error message.
Thank you.
 
![image](https://user-images.githubusercontent.com/28548036/37443922-51e35af2-2852-11e8-8821-bfe72b3e53bc.png)

**Comment by sumwale** [comment]
@swjung94 Thanks for the report. Has been mentioned on other channels like Slack too. Looking into this.

**Comment by sumwale** [comment]
#992 closed as duplicate

**Comment by rishitesh** [comment]
@swjung94 Please provide the schema for the table.

**Comment by swjung94** [comment]
@rishitesh 
Hi, the schema is like below, 
![image](https://user-images.githubusercontent.com/28548036/39170314-01b8a160-47d6-11e8-9a51-e6028ada17f9.png)

**Comment by dshirish** [comment]
Closing the issue as this has been fixed
