### ISSUE TITLE
Can I create diskstore on HDFS？

### ISSUE THREAD

**Issue by alexBaiJW** [SnappyDataInc/snappydata#990]
> We recommend using flash storage for optimal performance for SnappyData shared nothing persistence. Data can be saved out to stores like HDFS and S3 using SnappyData DataFrame APIs.

1，Can I create diskstore on HDFS?  From the document I think the answer is no, and I also has try it out.
2，If I store data on HDFS, Does it effect the performance compared storing data on local file system? What is the difference for that?  In my opinion, store on the local file system, just like the snappydata-self storage, but HDFS does not. So snappydata will not auto load the data on the HDFS when it start.

Is there anyone can explain it for me? Thanks advance!

**Comment by sumwale** [comment]
1. No direct HDFS storage support. You can use NFS (or SAN) though normally local disk is recommended. With column tables, NFS/SAN might be ok with high performance LAN.

2. HDFS can be used for periodically dumping a snapshot of entire data, or re-populating the tables, but cannot be used directly for persistence as mentioned.

This is likely to change in next releases (1.1 or 1.2) when direct parquet format persistence over HDFS/S3/... will be added.
